In [1]:
import pandas as pd

### 1 INEGI 2019

Obtener listado único de municipios y listado único de localidades de inegi de 2019 con sus claves.

In [2]:
path_dataset_inegi_2019 = '../../data/inegi/dataset_inegi_clean_2019.csv'
#dataset_inegi_clean = pd.read_csv(path_dataset_inegi_2022, encoding='utf-8', dtype={'CVE_ENT': str, 'CVE_MUN': str, 'CVE_LOC': str})
dataset_inegi_2019 = pd.read_csv(path_dataset_inegi_2019)

In [3]:
dataset_inegi_2019['KEY_inegi_municipio'] = dataset_inegi_2019['Entidad_c_inegi'].astype(str) + '-' + dataset_inegi_2019[
    'Municipio_c_inegi'].astype(str) 
dataset_inegi_2019['KEY_inegi_localidad'] = dataset_inegi_2019['Municipio_c_inegi'].astype(str) + '-' + dataset_inegi_2019['Localidad_c_inegi'].astype(str)

### 1.2.1 INEGI 2019 Localidades únicas para cada año. GUERRERO

In [4]:
INEGI_UNIQUELOC_2019 = dataset_inegi_2019

INEGI_UNIQUELOC_2019 = INEGI_UNIQUELOC_2019.drop_duplicates()

In [5]:
INEGI_UNIQUELOC_2019.shape

(299570, 12)

In [6]:
INEGI_UNIQUELOC_2019.columns

Index(['CVE_ENT', 'Entidad_inegi', 'CVE_MUN', 'Municipio_inegi', 'CVE_LOC',
       'Localidad_inegi', 'POB_TOTAL', 'Entidad_c_inegi', 'Municipio_c_inegi',
       'Localidad_c_inegi', 'KEY_inegi_municipio', 'KEY_inegi_localidad'],
      dtype='object')

In [7]:
INEGI_UNIQUELOC_2019_guerrero = INEGI_UNIQUELOC_2019[INEGI_UNIQUELOC_2019['Entidad_inegi'] == 'Guerrero']

In [8]:
INEGI_UNIQUELOC_2019_guerrero.shape

(9551, 12)

In [9]:
# Ordenar el DataFrame por Entidad_inegi, Municipio_inegi y Localidad_inegi
df_sorted = INEGI_UNIQUELOC_2019_guerrero.sort_values(by=['Entidad_inegi', 'Municipio_inegi', 'Localidad_inegi'])

# Identificar duplicados basados en Entidad_inegi, Municipio_inegi y Localidad_inegi
duplicados = df_sorted[df_sorted.duplicated(subset=['Entidad_inegi', 'Municipio_inegi', 'Localidad_inegi'], keep=False)]
print("Número de rows con base en Entidad, Municipio y Localidad: " , duplicados.shape)

Número de rows con base en Entidad, Municipio y Localidad:  (647, 12)

In [10]:
# Contar duplicados agrupados por Entidad_inegi, Municipio_inegi y Localidad_inegi
conteo_duplicados = duplicados.groupby(['Entidad_inegi', 'Municipio_inegi', 'Localidad_inegi']).size().reset_index(name='Numero_Duplicados')

# Ordenar por el número de duplicados en orden descendente
conteo_duplicados = conteo_duplicados.sort_values(by='Numero_Duplicados', ascending=False)

# Mostrar el conteo de duplicados ordenado por count
conteo_duplicados

,Entidad_inegi,Municipio_inegi,Localidad_inegi,Numero_Duplicados
257,Guerrero,Zirándaro,El Guayabo,6
279,Guerrero,Zirándaro,Las Juntas,5
208,Guerrero,Técpan de Galeana,El Rincón,5
39,Guerrero,Coahuayutla de José María Izazaga,El Jazmín,4
286,Guerrero,Zirándaro,Potrerillos,4
...,...,...,...,...
110,Guerrero,Cutzamala de Pinzón,Las Juntas,2
111,Guerrero,Cutzamala de Pinzón,Loma Bonita,2
113,Guerrero,Florencio Villarreal,Vista Hermosa,2
114,Guerrero,General Heliodoro Castillo,Barrio Nuevo,2
145,Guerrero,Olinalá,Los Mangos,2

In [11]:
total_duplicados = conteo_duplicados['Numero_Duplicados'].sum()

In [12]:
total_duplicados

647

In [13]:
# Step 1 & 2: Group by 'municipio' and 'localidad', then find the row with the maximum 'pob' within each group
INEGI_UNIQUELOC_2019_guerrero = INEGI_UNIQUELOC_2019_guerrero.loc[INEGI_UNIQUELOC_2019_guerrero.groupby(['Municipio_inegi', 'Localidad_inegi'])['POB_TOTAL'].idxmax()]

# This DataFrame now contains the localidades with the greatest 'pob' for each unique 'municipio'-'localidad' combination

In [14]:
INEGI_UNIQUELOC_2019_guerrero.drop(columns=["KEY_inegi_municipio"], inplace=True)

In [15]:
INEGI_UNIQUELOC_2019_guerrero

,CVE_ENT,Entidad_inegi,CVE_MUN,Municipio_inegi,CVE_LOC,Localidad_inegi,POB_TOTAL,Entidad_c_inegi,Municipio_c_inegi,Localidad_c_inegi,KEY_inegi_localidad
104542,12,Guerrero,1,Acapulco de Juárez,377,10 de Abril,879,guerrero,acapulco de juarez,10 de abril,acapulco de juarez-10 de abril
104721,12,Guerrero,1,Acapulco de Juárez,758,13 de Diciembre,19,guerrero,acapulco de juarez,13 de diciembre,acapulco de juarez-13 de diciembre
104435,12,Guerrero,1,Acapulco de Juárez,1,Acapulco de Juárez,658609,guerrero,acapulco de juarez,acapulco de juarez,acapulco de juarez-acapulco de juarez
104572,12,Guerrero,1,Acapulco de Juárez,462,Agropecuaria,0,guerrero,acapulco de juarez,agropecuaria,acapulco de juarez-agropecuaria
104652,12,Guerrero,1,Acapulco de Juárez,666,Agua Salada [Estación Hidrométrica],0,guerrero,acapulco de juarez,agua salada [estacion hidrometrica],acapulco de juarez-agua salada [estacion hidro...
...,...,...,...,...,...,...,...,...,...,...,...
113404,12,Guerrero,74,Zitlala,34,Totola,73,guerrero,zitlala,totola,zitlala-totola
113395,12,Guerrero,74,Zitlala,20,Viramontes,415,guerrero,zitlala,viramontes,zitlala-viramontes
113396,12,Guerrero,74,Zitlala,22,Yetlancingo,639,guerrero,zitlala,yetlancingo,zitlala-yetlancingo
113403,12,Guerrero,74,Zitlala,32,Zacayahutla,0,guerrero,zitlala,zacayahutla,zitlala-zacayahutla
113377,12,Guerrero,74,Zitlala,1,Zitlala,6077,guerrero,zitlala,zitlala,zitlala-zitlala

In [16]:
INEGI_UNIQUELOC_2019_guerrero.shape

(9194, 11)

In [17]:
INEGI_UNIQUELOC_2019_guerrero.drop_duplicates(subset=['Municipio_inegi', 'Localidad_inegi'], inplace=True)

In [18]:
INEGI_UNIQUELOC_2019_guerrero.to_csv('../../data/productores_beneficiarios 2019-2022/diccionarios_E3/2019/INEGI_UNIQUELOC_2019_guerrero.csv', index=False, encoding='utf-8')

El número total de rows para este dataset se calcula así: INEGI_UNIQUELOC_2019_guerrero - total_duplicados + conteo_duplicados. Esto sucede así porque el total_duplicados + conteo_duplicados es igual al número de rows que sí vamos a incluir en el dataset, es decir; los rows con entidad, municipio, y localidad que sean iguales de los cuales seleccionaremos la localidad con mayor número de habitantes.

### 1.2.2 INEGI 2019 Localidades únicas para cada año. CHIAPAS

In [19]:
INEGI_UNIQUELOC_2019_chiapas = INEGI_UNIQUELOC_2019[INEGI_UNIQUELOC_2019['Entidad_inegi'] == 'Chiapas']

In [20]:
INEGI_UNIQUELOC_2019_chiapas.shape

(27219, 12)

In [21]:
# Ordenar el DataFrame por Entidad_inegi, Municipio_inegi y Localidad_inegi
df_sorted = INEGI_UNIQUELOC_2019_chiapas.sort_values(by=['Entidad_inegi', 'Municipio_inegi', 'Localidad_inegi'])

# Identificar duplicados basados en Entidad_inegi, Municipio_inegi y Localidad_inegi
duplicados = df_sorted[df_sorted.duplicated(subset=['Entidad_inegi', 'Municipio_inegi', 'Localidad_inegi'], keep=False)]
print("Número de rows con base en Entidad, Municipio y Localidad: " , duplicados.shape)

Número de rows con base en Entidad, Municipio y Localidad:  (7839, 12)

In [22]:
# Contar duplicados agrupados por Entidad_inegi, Municipio_inegi y Localidad_inegi
conteo_duplicados = duplicados.groupby(['Entidad_inegi', 'Municipio_inegi', 'Localidad_inegi']).size().reset_index(name='Numero_Duplicados')

# Ordenar por el número de duplicados en orden descendente
conteo_duplicados = conteo_duplicados.sort_values(by='Numero_Duplicados', ascending=False)

# Mostrar el conteo de duplicados ordenado por count
conteo_duplicados

     Entidad_inegi     Municipio_inegi Localidad_inegi  Numero_Duplicados
2059       Chiapas         Villa Corzo     El Recuerdo                 28
1577       Chiapas          Pijijiapan     San Antonio                 24
2420       Chiapas         Villaflores     San Antonio                 22
1082       Chiapas            Ocosingo       Guadalupe                 21
1415       Chiapas            Palenque        San José                 21
...            ...                 ...             ...                ...
967        Chiapas           Mezcalapa    Grano de Oro                  2
966        Chiapas           Mezcalapa       El Retazo                  2
964        Chiapas             Mazatán      Santa Rosa                  2
963        Chiapas             Mazatán      San Martín                  2
2506       Chiapas  Ángel Albino Corzo      San Miguel                  2

[2507 rows x 4 columns]

In [23]:
total_duplicados = conteo_duplicados['Numero_Duplicados'].sum()

In [24]:
total_duplicados

7839

In [25]:
# Step 1 & 2: Group by 'municipio' and 'localidad', then find the row with the maximum 'pob' within each group
INEGI_UNIQUELOC_2019_chiapas = INEGI_UNIQUELOC_2019_chiapas.loc[INEGI_UNIQUELOC_2019_chiapas.groupby(['Municipio_inegi', 'Localidad_inegi'])['POB_TOTAL'].idxmax()]

# This DataFrame now contains the localidades with the greatest 'pob' for each unique 'municipio'-'localidad' combination

In [26]:
INEGI_UNIQUELOC_2019_chiapas.drop(columns=["KEY_inegi_municipio"], inplace=True)

In [27]:
INEGI_UNIQUELOC_2019_chiapas

,CVE_ENT,Entidad_inegi,CVE_MUN,Municipio_inegi,CVE_LOC,Localidad_inegi,POB_TOTAL,Entidad_c_inegi,Municipio_c_inegi,Localidad_c_inegi,KEY_inegi_localidad
32651,7,Chiapas,1,Acacoyagua,218,3 Garcías,6,chiapas,acacoyagua,3 garcias,acacoyagua-3 garcias
32653,7,Chiapas,1,Acacoyagua,220,3 Hermanos,0,chiapas,acacoyagua,3 hermanos,acacoyagua-3 hermanos
32517,7,Chiapas,1,Acacoyagua,1,Acacoyagua,8092,chiapas,acacoyagua,acacoyagua,acacoyagua-acacoyagua
32628,7,Chiapas,1,Acacoyagua,193,Alonso Morales,3,chiapas,acacoyagua,alonso morales,acacoyagua-alonso morales
32519,7,Chiapas,1,Acacoyagua,3,Arvin,26,chiapas,acacoyagua,arvin,acacoyagua-arvin
...,...,...,...,...,...,...,...,...,...,...,...
33584,7,Chiapas,8,Ángel Albino Corzo,43,Tierra Blanca (Pequeñeces),19,chiapas,angel albino corzo,tierra blanca (pequeneces),angel albino corzo-tierra blanca (pequeneces)
33601,7,Chiapas,8,Ángel Albino Corzo,101,Tres Estrellas,4,chiapas,angel albino corzo,tres estrellas,angel albino corzo-tres estrellas
33758,7,Chiapas,8,Ángel Albino Corzo,737,Tres Hermanos,5,chiapas,angel albino corzo,tres hermanos,angel albino corzo-tres hermanos
33632,7,Chiapas,8,Ángel Albino Corzo,163,Venecia,0,chiapas,angel albino corzo,venecia,angel albino corzo-venecia
33659,7,Chiapas,8,Ángel Albino Corzo,586,Villahermosa,0,chiapas,angel albino corzo,villahermosa,angel albino corzo-villahermosa

In [28]:
INEGI_UNIQUELOC_2019_chiapas.shape

(21887, 11)

In [29]:
INEGI_UNIQUELOC_2019_chiapas.drop_duplicates(subset=['Municipio_inegi', 'Localidad_inegi'], inplace=True)

In [30]:
INEGI_UNIQUELOC_2019_chiapas.to_csv('../../data/productores_beneficiarios 2019-2022/diccionarios_E3/2019/INEGI_UNIQUELOC_2019_chiapas.csv', index=False, encoding='utf-8')

### 1.2.3 INEGI 2019 Localidades únicas para cada año. PUEBLA

In [31]:
INEGI_UNIQUELOC_2019_puebla = INEGI_UNIQUELOC_2019[INEGI_UNIQUELOC_2019['Entidad_inegi'] == 'Puebla']

In [32]:
INEGI_UNIQUELOC_2019_puebla.shape

(8017, 12)

In [33]:
# Ordenar el DataFrame por Entidad_inegi, Municipio_inegi y Localidad_inegi
df_sorted = INEGI_UNIQUELOC_2019_puebla.sort_values(by=['Entidad_inegi', 'Municipio_inegi', 'Localidad_inegi'])

# Identificar duplicados basados en Entidad_inegi, Municipio_inegi y Localidad_inegi
duplicados = df_sorted[df_sorted.duplicated(subset=['Entidad_inegi', 'Municipio_inegi', 'Localidad_inegi'], keep=False)]
print("Número de rows con base en Entidad, Municipio y Localidad: " , duplicados.shape)

Número de rows con base en Entidad, Municipio y Localidad:  (570, 12)

In [34]:
# Contar duplicados agrupados por Entidad_inegi, Municipio_inegi y Localidad_inegi
conteo_duplicados = duplicados.groupby(['Entidad_inegi', 'Municipio_inegi', 'Localidad_inegi']).size().reset_index(name='Numero_Duplicados')

# Ordenar por el número de duplicados en orden descendente
conteo_duplicados = conteo_duplicados.sort_values(by='Numero_Duplicados', ascending=False)

# Mostrar el conteo de duplicados ordenado por count
conteo_duplicados

,Entidad_inegi,Municipio_inegi,Localidad_inegi,Numero_Duplicados
186,Puebla,San Salvador Huixcolotla,San Salvador Huixcolotla,6
40,Puebla,Chapulco,Chapulco,5
136,Puebla,Ocoyucan,San Bernardino Chalchihuapan,4
194,Puebla,San Salvador el Seco,Santa María Coatepec,4
205,Puebla,Tehuacán,San Cristóbal Tepeteopan,4
...,...,...,...,...
99,Puebla,Huejotzingo,Santo Domingo Ciénega Honda,2
100,Puebla,Hueytamalco,San Carlos,2
101,Puebla,Hueytamalco,San Luis,2
102,Puebla,Hueytlalpan,El Cuyo,2
260,Puebla,Zongozotla,Zongozotla,2

In [35]:
total_duplicados = conteo_duplicados['Numero_Duplicados'].sum()

In [36]:
total_duplicados

570

In [37]:
# Step 1 & 2: Group by 'municipio' and 'localidad', then find the row with the maximum 'pob' within each group
INEGI_UNIQUELOC_2019_puebla = INEGI_UNIQUELOC_2019_puebla.loc[INEGI_UNIQUELOC_2019_puebla.groupby(['Municipio_inegi', 'Localidad_inegi'])['POB_TOTAL'].idxmax()]

# This DataFrame now contains the localidades with the greatest 'pob' for each unique 'municipio'-'localidad' combination

In [38]:
INEGI_UNIQUELOC_2019_puebla.drop(columns=["KEY_inegi_municipio"], inplace=True)

In [39]:
INEGI_UNIQUELOC_2019_puebla

,CVE_ENT,Entidad_inegi,CVE_MUN,Municipio_inegi,CVE_LOC,Localidad_inegi,POB_TOTAL,Entidad_c_inegi,Municipio_c_inegi,Localidad_c_inegi,KEY_inegi_localidad
186398,21,Puebla,1,Acajete,1,Acajete,13922,puebla,acajete,acajete,acajete-acajete
186399,21,Puebla,1,Acajete,2,Acultzingo,1,puebla,acajete,acultzingo,acajete-acultzingo
186468,21,Puebla,1,Acajete,90,Amacuatitas,21,puebla,acajete,amacuatitas,acajete-amacuatitas
186416,21,Puebla,1,Acajete,24,Apango de Zaragoza,3032,puebla,acajete,apango de zaragoza,acajete-apango de zaragoza
186413,21,Puebla,1,Acajete,18,Buenavista,39,puebla,acajete,buenavista,acajete-buenavista
...,...,...,...,...,...,...,...,...,...,...,...
194394,21,Puebla,217,Zoquitlán,65,Xoloxtepec,191,puebla,zoquitlan,xoloxtepec,zoquitlan-xoloxtepec
194405,21,Puebla,217,Zoquitlán,242,Zoquitlanzacualco,518,puebla,zoquitlan,zoquitlanzacualco,zoquitlan-zoquitlanzacualco
194358,21,Puebla,217,Zoquitlán,1,Zoquitlán,3404,puebla,zoquitlan,zoquitlan,zoquitlan-zoquitlan
194411,21,Puebla,217,Zoquitlán,663,Íxcatl,34,puebla,zoquitlan,ixcatl,zoquitlan-ixcatl
194362,21,Puebla,217,Zoquitlán,5,Ízhuapa,709,puebla,zoquitlan,izhuapa,zoquitlan-izhuapa

In [40]:
INEGI_UNIQUELOC_2019_puebla.shape

(7708, 11)

In [41]:
INEGI_UNIQUELOC_2019_puebla.drop_duplicates(subset=['Municipio_inegi', 'Localidad_inegi'], inplace=True)

In [42]:
INEGI_UNIQUELOC_2019_puebla.to_csv('../../data/productores_beneficiarios 2019-2022/diccionarios_E3/2019/INEGI_UNIQUELOC_2019_puebla.csv', index=False, encoding='utf-8')

### 1.2.4 INEGI 2019 Localidades únicas para cada año. MEXICO

In [43]:
INEGI_UNIQUELOC_2019_mexico = INEGI_UNIQUELOC_2019[INEGI_UNIQUELOC_2019['Entidad_inegi'] == 'México']

In [44]:
INEGI_UNIQUELOC_2019_mexico.shape

(5262, 12)

In [45]:
# Ordenar el DataFrame por Entidad_inegi, Municipio_inegi y Localidad_inegi
df_sorted = INEGI_UNIQUELOC_2019_mexico.sort_values(by=['Entidad_inegi', 'Municipio_inegi', 'Localidad_inegi'])

# Identificar duplicados basados en Entidad_inegi, Municipio_inegi y Localidad_inegi
duplicados = df_sorted[df_sorted.duplicated(subset=['Entidad_inegi', 'Municipio_inegi', 'Localidad_inegi'], keep=False)]
print("Número de rows con base en Entidad, Municipio y Localidad: " , duplicados.shape)

Número de rows con base en Entidad, Municipio y Localidad:  (85, 12)

In [46]:
# Contar duplicados agrupados por Entidad_inegi, Municipio_inegi y Localidad_inegi
conteo_duplicados = duplicados.groupby(['Entidad_inegi', 'Municipio_inegi', 'Localidad_inegi']).size().reset_index(name='Numero_Duplicados')

# Ordenar por el número de duplicados en orden descendente
conteo_duplicados = conteo_duplicados.sort_values(by='Numero_Duplicados', ascending=False)

# Mostrar el conteo de duplicados ordenado por count
conteo_duplicados

,Entidad_inegi,Municipio_inegi,Localidad_inegi,Numero_Duplicados
34,México,Tlatlaya,La Cofradía,4
39,México,Zumpango,Santa Lucía,3
11,México,Luvianos,El Pueblito,3
16,México,Luvianos,Los Bancos,3
23,México,Santo Tomás,El Aguacate,2
24,México,Sultepec,El Salitre,2
25,México,Sultepec,La Ciénega,2
26,México,Tejupilco,La Calera,2
27,México,Tejupilco,La Mesa,2
28,México,Temascaltepec,El Salitre,2
29,México,Tenango del Valle,Las Crucecitas,2
30,México,Texcoco,Colonia Lázaro Cárdenas,2
21,México,Otzoloapan,El Limón,2
31,México,Tlatlaya,Cuadrilla Nueva,2
32,México,Tlatlaya,El Coyol,2
33,México,Tlatlaya,El Mango,2
35,México,Tlatlaya,La Parota,2
36,México,Tlatlaya,Tierra Blanca,2
37,México,Zacualpan,La Hacienda,2
38,México,Zacualpan,Tres Cruces,2
22,México,San Felipe del Progreso,Mesa de la Agüita,2
0,México,Amatepec,Cuadrilla Nueva,2
1,México,Amatepec,El Zapote,2
19,México,Luvianos,Tremesinos,2
2,México,Amatepec,La Mina,2
3,México,Amatepec,Las Ceibas,2
4,México,Amatepec,Los Encinos,2
5,México,Amatepec,Los Timbres,2
6,México,Huehuetoca,Ex-Hacienda de Xalpa,2
7,México,Ixtapaluca,La Cañada,2
8,México,La Paz,Lomas de San Sebastián,2
9,México,Luvianos,Caja de Agua,2
10,México,Luvianos,El Limón,2
12,México,Luvianos,La Laguna,2
13,México,Luvianos,Las Anonas,2
14,México,Luvianos,Las Juntas,2
15,México,Luvianos,Los Arrayanes,2
17,México,Luvianos,Los Pinzanes,2
18,México,Luvianos,Rancho Viejo,2
20,México,Otumba,Santiago Tolman,2

In [47]:
conteo_duplicados.shape

(40, 4)

In [48]:
total_duplicados = conteo_duplicados['Numero_Duplicados'].sum()

In [49]:
total_duplicados

85

In [50]:
# Step 1 & 2: Group by 'municipio' and 'localidad', then find the row with the maximum 'pob' within each group
INEGI_UNIQUELOC_2019_mexico = INEGI_UNIQUELOC_2019_mexico.loc[INEGI_UNIQUELOC_2019_mexico.groupby(['Municipio_inegi', 'Localidad_inegi'])['POB_TOTAL'].idxmax()]

# This DataFrame now contains the localidades with the greatest 'pob' for each unique 'municipio'-'localidad' combination

In [51]:
INEGI_UNIQUELOC_2019_mexico.drop(columns=["KEY_inegi_municipio"], inplace=True)

In [52]:
INEGI_UNIQUELOC_2019_mexico

,CVE_ENT,Entidad_inegi,CVE_MUN,Municipio_inegi,CVE_LOC,Localidad_inegi,POB_TOTAL,Entidad_c_inegi,Municipio_c_inegi,Localidad_c_inegi,KEY_inegi_localidad
138741,15,México,1,Acambay de Ruíz Castañeda,2,Agostadero (San José Agostadero),587,mexico,acambay de ruiz castaneda,agostadero (san jose agostadero),acambay de ruiz castaneda-agostadero (san jose...
138742,15,México,1,Acambay de Ruíz Castañeda,3,Agua Limpia,272,mexico,acambay de ruiz castaneda,agua limpia,acambay de ruiz castaneda-agua limpia
138805,15,México,1,Acambay de Ruíz Castañeda,79,Barrancas,109,mexico,acambay de ruiz castaneda,barrancas,acambay de ruiz castaneda-barrancas
138833,15,México,1,Acambay de Ruíz Castañeda,117,Barrio de Candeje,329,mexico,acambay de ruiz castaneda,barrio de candeje,acambay de ruiz castaneda-barrio de candeje
138762,15,México,1,Acambay de Ruíz Castañeda,25,Barrio de Guadalupe,332,mexico,acambay de ruiz castaneda,barrio de guadalupe,acambay de ruiz castaneda-barrio de guadalupe
...,...,...,...,...,...,...,...,...,...,...,...
143554,15,México,120,Zumpango,59,Santa María de Guadalupe,4942,mexico,zumpango,santa maria de guadalupe,zumpango-santa maria de guadalupe
143541,15,México,120,Zumpango,24,Valle Hermoso,42,mexico,zumpango,valle hermoso,zumpango-valle hermoso
143610,15,México,120,Zumpango,206,Villas de Zumpango [Conjunto Urbano],3744,mexico,zumpango,villas de zumpango [conjunto urbano],zumpango-villas de zumpango [conjunto urbano]
143608,15,México,120,Zumpango,204,Villas de la Laguna,15306,mexico,zumpango,villas de la laguna,zumpango-villas de la laguna
143531,15,México,120,Zumpango,1,Zumpango de Ocampo,53362,mexico,zumpango,zumpango de ocampo,zumpango-zumpango de ocampo

In [53]:
INEGI_UNIQUELOC_2019_mexico.shape

(5217, 11)

In [54]:
INEGI_UNIQUELOC_2019_mexico.drop_duplicates(subset=['Municipio_inegi', 'Localidad_inegi'], inplace=True)

In [55]:
INEGI_UNIQUELOC_2019_mexico.to_csv('../../data/productores_beneficiarios 2019-2022/diccionarios_E3/2019/INEGI_UNIQUELOC_2019_mexico.csv', index=False, encoding='utf-8')

### 1.2.5 INEGI 2019 Localidades únicas para cada año. Guanajuato

In [56]:
INEGI_UNIQUELOC_2019_guanajuato = INEGI_UNIQUELOC_2019[INEGI_UNIQUELOC_2019['Entidad_inegi'] == 'Guanajuato']

In [57]:
INEGI_UNIQUELOC_2019_guanajuato.shape

(11507, 12)

In [58]:
# Ordenar el DataFrame por Entidad_inegi, Municipio_inegi y Localidad_inegi
df_sorted = INEGI_UNIQUELOC_2019_guanajuato.sort_values(by=['Entidad_inegi', 'Municipio_inegi', 'Localidad_inegi'])

# Identificar duplicados basados en Entidad_inegi, Municipio_inegi y Localidad_inegi
duplicados = df_sorted[df_sorted.duplicated(subset=['Entidad_inegi', 'Municipio_inegi', 'Localidad_inegi'], keep=False)]
print("Número de rows con base en Entidad, Municipio y Localidad: " , duplicados.shape)

Número de rows con base en Entidad, Municipio y Localidad:  (701, 12)

In [59]:
# Contar duplicados agrupados por Entidad_inegi, Municipio_inegi y Localidad_inegi
conteo_duplicados = duplicados.groupby(['Entidad_inegi', 'Municipio_inegi', 'Localidad_inegi']).size().reset_index(name='Numero_Duplicados')

# Ordenar por el número de duplicados en orden descendente
conteo_duplicados = conteo_duplicados.sort_values(by='Numero_Duplicados', ascending=False)

# Mostrar el conteo de duplicados ordenado por count
conteo_duplicados

,Entidad_inegi,Municipio_inegi,Localidad_inegi,Numero_Duplicados
53,Guanajuato,Dolores Hidalgo Cuna de la Independencia Nacional,La Luz,7
51,Guanajuato,Dolores Hidalgo Cuna de la Independencia Nacional,La Esperanza,5
54,Guanajuato,Dolores Hidalgo Cuna de la Independencia Nacional,La Providencia,4
174,Guanajuato,Salamanca,Ninguno [Transportes de Carga],4
202,Guanajuato,San Felipe,La Soledad,4
...,...,...,...,...
116,Guanajuato,León,Rancho Viejo,2
114,Guanajuato,León,Ninguno [Club Cinegético],2
113,Guanajuato,León,Ninguno,2
112,Guanajuato,León,Las Presitas,2
323,Guanajuato,Xichú,Ojo de Agua,2

In [60]:
conteo_duplicados.shape

(324, 4)

In [61]:
total_duplicados = conteo_duplicados['Numero_Duplicados'].sum()

In [62]:
total_duplicados

701

In [63]:
# Step 1 & 2: Group by 'municipio' and 'localidad', then find the row with the maximum 'pob' within each group
INEGI_UNIQUELOC_2019_guanajuato = INEGI_UNIQUELOC_2019_guanajuato.loc[INEGI_UNIQUELOC_2019_guanajuato.groupby(['Municipio_inegi', 'Localidad_inegi'])['POB_TOTAL'].idxmax()]

# This DataFrame now contains the localidades with the greatest 'pob' for each unique 'municipio'-'localidad' combination

In [64]:
INEGI_UNIQUELOC_2019_guanajuato.drop(columns=["KEY_inegi_municipio"], inplace=True)

In [65]:
INEGI_UNIQUELOC_2019_guanajuato

,CVE_ENT,Entidad_inegi,CVE_MUN,Municipio_inegi,CVE_LOC,Localidad_inegi,POB_TOTAL,Entidad_c_inegi,Municipio_c_inegi,Localidad_c_inegi,KEY_inegi_localidad
92928,11,Guanajuato,1,Abasolo,1,Abasolo,29002,guanajuato,abasolo,abasolo,abasolo-abasolo
93160,11,Guanajuato,1,Abasolo,492,Abel Delgado (La Lobera),76,guanajuato,abasolo,abel delgado (la lobera),abasolo-abel delgado (la lobera)
92930,11,Guanajuato,1,Abasolo,3,Agua Blanca,7,guanajuato,abasolo,agua blanca,abasolo-agua blanca
93143,11,Guanajuato,1,Abasolo,439,Ahualulco,50,guanajuato,abasolo,ahualulco,abasolo-ahualulco
92932,11,Guanajuato,1,Abasolo,6,Alameda de Álvarez,124,guanajuato,abasolo,alameda de alvarez,abasolo-alameda de alvarez
...,...,...,...,...,...,...,...,...,...,...,...
104377,11,Guanajuato,46,Yuriria,93,Tinaja de Pastores,934,guanajuato,yuriria,tinaja de pastores,yuriria-tinaja de pastores
104321,11,Guanajuato,46,Yuriria,26,Xoconoxtle,731,guanajuato,yuriria,xoconoxtle,yuriria-xoconoxtle
104300,11,Guanajuato,46,Yuriria,1,Yuriria,25845,guanajuato,yuriria,yuriria,yuriria-yuriria
104380,11,Guanajuato,46,Yuriria,98,Zapotitos,312,guanajuato,yuriria,zapotitos,yuriria-zapotitos
104381,11,Guanajuato,46,Yuriria,100,Zepeda,0,guanajuato,yuriria,zepeda,yuriria-zepeda

In [66]:
INEGI_UNIQUELOC_2019_guanajuato.shape

(11130, 11)

In [67]:
INEGI_UNIQUELOC_2019_guanajuato.drop_duplicates(subset=['Municipio_inegi', 'Localidad_inegi'], inplace=True)

In [68]:
INEGI_UNIQUELOC_2019_guanajuato.to_csv('../../data/productores_beneficiarios 2019-2022/diccionarios_E3/2019/INEGI_UNIQUELOC_2019_guanajuato.csv', index=False, encoding='utf-8')

### 1.2.6 INEGI 2019 Localidades únicas para cada año. QUERETARO

In [69]:
INEGI_UNIQUELOC_2019_queretaro = INEGI_UNIQUELOC_2019[INEGI_UNIQUELOC_2019['Entidad_inegi'] == 'Querétaro']

In [70]:
INEGI_UNIQUELOC_2019_queretaro.shape

(2883, 12)

In [71]:
# Ordenar el DataFrame por Entidad_inegi, Municipio_inegi y Localidad_inegi
df_sorted = INEGI_UNIQUELOC_2019_queretaro.sort_values(by=['Entidad_inegi', 'Municipio_inegi', 'Localidad_inegi'])

# Identificar duplicados basados en Entidad_inegi, Municipio_inegi y Localidad_inegi
duplicados = df_sorted[df_sorted.duplicated(subset=['Entidad_inegi', 'Municipio_inegi', 'Localidad_inegi'], keep=False)]
print("Número de rows con base en Entidad, Municipio y Localidad: " , duplicados.shape)

Número de rows con base en Entidad, Municipio y Localidad:  (104, 12)

In [72]:
# Contar duplicados agrupados por Entidad_inegi, Municipio_inegi y Localidad_inegi
conteo_duplicados = duplicados.groupby(['Entidad_inegi', 'Municipio_inegi', 'Localidad_inegi']).size().reset_index(name='Numero_Duplicados')

# Ordenar por el número de duplicados en orden descendente
conteo_duplicados = conteo_duplicados.sort_values(by='Numero_Duplicados', ascending=False)

# Mostrar el conteo de duplicados ordenado por count
conteo_duplicados

,Entidad_inegi,Municipio_inegi,Localidad_inegi,Numero_Duplicados
49,Querétaro,Tolimán,El Sauz,3
23,Querétaro,Jalpan de Serra,El Llano,3
10,Querétaro,El Marqués,El Rosario,3
12,Querétaro,El Marqués,Familia Hernández,3
38,Querétaro,Querétaro,Casa Blanca,2
29,Querétaro,Landa de Matamoros,El Gavilán,2
30,Querétaro,Landa de Matamoros,La Reforma,2
31,Querétaro,Landa de Matamoros,Tres Lagunas,2
32,Querétaro,Peñamiller,El Cantoncito,2
33,Querétaro,Peñamiller,El Zapote II,2
34,Querétaro,Pinal de Amoles,El Naranjo,2
35,Querétaro,Pinal de Amoles,La Cañada,2
36,Querétaro,Pinal de Amoles,Puerto Hondo,2
37,Querétaro,Pinal de Amoles,San Isidro,2
39,Querétaro,Querétaro,El Bordo,2
27,Querétaro,Jalpan de Serra,La Cuchilla,2
40,Querétaro,Querétaro,El Ranchito,2
41,Querétaro,Querétaro,El Refugio,2
42,Querétaro,Querétaro,La Esperanza,2
43,Querétaro,Querétaro,La Mesa,2
44,Querétaro,Querétaro,La Purísima,2
45,Querétaro,San Juan del Río,La Nueva Esperanza,2
46,Querétaro,Tequisquiapan,El Arenal,2
47,Querétaro,Tequisquiapan,La Soledad,2
48,Querétaro,Tequisquiapan,Los Lobos,2
28,Querétaro,Jalpan de Serra,Las Lagunitas,2
0,Querétaro,Amealco de Bonfil,El Capulín,2
26,Querétaro,Jalpan de Serra,La Ceiba,2
13,Querétaro,El Marqués,La Laborcilla,2
2,Querétaro,Arroyo Seco,La Huastequita,2
3,Querétaro,Arroyo Seco,Las Adjuntas,2
4,Querétaro,Cadereyta de Montes,Casas Viejas,2
5,Querétaro,Cadereyta de Montes,El Ranchito,2
6,Querétaro,Cadereyta de Montes,Las Joyas,2
7,Querétaro,Colón,El Leoncito,2
8,Querétaro,Colón,Palmas,2
9,Querétaro,El Marqués,El Paraíso,2
11,Querétaro,El Marqués,Familia González,2
14,Querétaro,El Marqués,Los Pinos,2
1,Querétaro,Arroyo Seco,El Rejalgar,2
15,Querétaro,Ezequiel Montes,El Cerrito,2
16,Querétaro,Ezequiel Montes,El Ordaz,2
17,Querétaro,Ezequiel Montes,La Soledad,2
18,Querétaro,Ezequiel Montes,Rancho el Chiquihuite,2
19,Querétaro,Ezequiel Montes,Rancho el Junal,2
20,Querétaro,Ezequiel Montes,Rancho la Puerta de San José,2
21,Querétaro,Huimilpan,La Bomba,2
22,Querétaro,Jalpan de Serra,El Limón,2
24,Querétaro,Jalpan de Serra,El Naranjo,2
25,Querétaro,Jalpan de Serra,El Tigre,2

In [73]:
conteo_duplicados.shape

(50, 4)

In [74]:
total_duplicados = conteo_duplicados['Numero_Duplicados'].sum()

In [75]:
total_duplicados

104

In [76]:
# Step 1 & 2: Group by 'municipio' and 'localidad', then find the row with the maximum 'pob' within each group
INEGI_UNIQUELOC_2019_queretaro = INEGI_UNIQUELOC_2019_queretaro.loc[INEGI_UNIQUELOC_2019_queretaro.groupby(['Municipio_inegi', 'Localidad_inegi'])['POB_TOTAL'].idxmax()]

# This DataFrame now contains the localidades with the greatest 'pob' for each unique 'municipio'-'localidad' combination

In [77]:
INEGI_UNIQUELOC_2019_queretaro.drop(columns=["KEY_inegi_municipio"], inplace=True)

In [78]:
INEGI_UNIQUELOC_2019_queretaro

,CVE_ENT,Entidad_inegi,CVE_MUN,Municipio_inegi,CVE_LOC,Localidad_inegi,POB_TOTAL,Entidad_c_inegi,Municipio_c_inegi,Localidad_c_inegi,KEY_inegi_localidad
194416,22,Querétaro,1,Amealco de Bonfil,2,Agua Blanca,80,queretaro,amealco de bonfil,agua blanca,amealco de bonfil-agua blanca
194415,22,Querétaro,1,Amealco de Bonfil,1,Amealco de Bonfil,7953,queretaro,amealco de bonfil,amealco de bonfil,amealco de bonfil-amealco de bonfil
194494,22,Querétaro,1,Amealco de Bonfil,98,Amárcigo (San Luis),45,queretaro,amealco de bonfil,amarcigo (san luis),amealco de bonfil-amarcigo (san luis)
194496,22,Querétaro,1,Amealco de Bonfil,100,Arroyo Hondo,10,queretaro,amealco de bonfil,arroyo hondo,amealco de bonfil-arroyo hondo
194503,22,Querétaro,1,Amealco de Bonfil,108,Barrio Ojo de Agua (San Miguel Tlaxcaltepec),245,queretaro,amealco de bonfil,barrio ojo de agua (san miguel tlaxcaltepec),amealco de bonfil-barrio ojo de agua (san migu...
...,...,...,...,...,...,...,...,...,...,...,...
197180,22,Querétaro,18,Tolimán,1,Tolimán,6290,queretaro,toliman,toliman,toliman-toliman
197242,22,Querétaro,18,Tolimán,87,Tuna Mantza (El Sabino),0,queretaro,toliman,tuna mantza (el sabino),toliman-tuna mantza (el sabino)
197245,22,Querétaro,18,Tolimán,92,Tuna Manza,28,queretaro,toliman,tuna manza,toliman-tuna manza
197240,22,Querétaro,18,Tolimán,85,Xithi [Rancho],2,queretaro,toliman,xithi [rancho],toliman-xithi [rancho]
197223,22,Querétaro,18,Tolimán,60,Zapote de los Uribe (El Zapote),15,queretaro,toliman,zapote de los uribe (el zapote),toliman-zapote de los uribe (el zapote)

In [79]:
INEGI_UNIQUELOC_2019_queretaro.shape

(2829, 11)

In [80]:
INEGI_UNIQUELOC_2019_queretaro.drop_duplicates(subset=['Municipio_inegi', 'Localidad_inegi'], inplace=True)

In [81]:
INEGI_UNIQUELOC_2019_queretaro.to_csv('../../data/productores_beneficiarios 2019-2022/diccionarios_E3/2019/INEGI_UNIQUELOC_2019_queretaro.csv', index=False, encoding='utf-8')

### 1.2.7 INEGI 2019 Localidades únicas para cada año. ZACATECAS

In [82]:
INEGI_UNIQUELOC_2019_zacatecas = INEGI_UNIQUELOC_2019[INEGI_UNIQUELOC_2019['Entidad_inegi'] == 'Zacatecas']

In [83]:
INEGI_UNIQUELOC_2019_zacatecas.shape

(6574, 12)

In [84]:
# Ordenar el DataFrame por Entidad_inegi, Municipio_inegi y Localidad_inegi
df_sorted = INEGI_UNIQUELOC_2019_zacatecas.sort_values(by=['Entidad_inegi', 'Municipio_inegi', 'Localidad_inegi'])

# Identificar duplicados basados en Entidad_inegi, Municipio_inegi y Localidad_inegi
duplicados = df_sorted[df_sorted.duplicated(subset=['Entidad_inegi', 'Municipio_inegi', 'Localidad_inegi'], keep=False)]
print("Número de rows con base en Entidad, Municipio y Localidad: " , duplicados.shape)

Número de rows con base en Entidad, Municipio y Localidad:  (294, 12)

In [85]:
# Contar duplicados agrupados por Entidad_inegi, Municipio_inegi y Localidad_inegi
conteo_duplicados = duplicados.groupby(['Entidad_inegi', 'Municipio_inegi', 'Localidad_inegi']).size().reset_index(name='Numero_Duplicados')

# Ordenar por el número de duplicados en orden descendente
conteo_duplicados = conteo_duplicados.sort_values(by='Numero_Duplicados', ascending=False)

# Mostrar el conteo de duplicados ordenado por count
conteo_duplicados

    Entidad_inegi         Municipio_inegi Localidad_inegi  Numero_Duplicados
16      Zacatecas               Fresnillo      El Refugio                  4
131     Zacatecas            Villa de Cos   San Francisco                  4
20      Zacatecas               Fresnillo        El Álamo                  3
128     Zacatecas            Villa de Cos       El Venado                  3
94      Zacatecas                   Pinos      San Isidro                  3
..            ...                     ...             ...                ...
44      Zacatecas               Guadalupe      Las Mangas                  2
43      Zacatecas               Guadalupe       La Tinaja                  2
42      Zacatecas  General Pánfilo Natera      San Rafael                  2
41      Zacatecas               Fresnillo      Santa Rosa                  2
137     Zacatecas               Zacatecas    Rancho Nuevo                  2

[138 rows x 4 columns]

In [86]:
conteo_duplicados.shape

(138, 4)

In [87]:
total_duplicados = conteo_duplicados['Numero_Duplicados'].sum()

In [88]:
total_duplicados

294

In [89]:
# Step 1 & 2: Group by 'municipio' and 'localidad', then find the row with the maximum 'pob' within each group
INEGI_UNIQUELOC_2019_zacatecas = INEGI_UNIQUELOC_2019_zacatecas.loc[INEGI_UNIQUELOC_2019_zacatecas.groupby(['Municipio_inegi', 'Localidad_inegi'])['POB_TOTAL'].idxmax()]

# This DataFrame now contains the localidades with the greatest 'pob' for each unique 'municipio'-'localidad' combination

In [90]:
INEGI_UNIQUELOC_2019_zacatecas.drop(columns=["KEY_inegi_municipio"], inplace=True)

In [91]:
INEGI_UNIQUELOC_2019_zacatecas

,CVE_ENT,Entidad_inegi,CVE_MUN,Municipio_inegi,CVE_LOC,Localidad_inegi,POB_TOTAL,Entidad_c_inegi,Municipio_c_inegi,Localidad_c_inegi,KEY_inegi_localidad
292997,32,Zacatecas,1,Apozol,2,Achoquen,37,zacatecas,apozol,achoquen,apozol-achoquen
292996,32,Zacatecas,1,Apozol,1,Apozol,2608,zacatecas,apozol,apozol,apozol-apozol
293042,32,Zacatecas,1,Apozol,93,Atarjea del Ocotito,3,zacatecas,apozol,atarjea del ocotito,apozol-atarjea del ocotito
293031,32,Zacatecas,1,Apozol,60,Atascadero,0,zacatecas,apozol,atascadero,apozol-atascadero
293000,32,Zacatecas,1,Apozol,7,Banco de Piedra,10,zacatecas,apozol,banco de piedra,apozol-banco de piedra
...,...,...,...,...,...,...,...,...,...,...,...
299403,32,Zacatecas,56,Zacatecas,55,Sardinas,8,zacatecas,zacatecas,sardinas,zacatecas-sardinas
299425,32,Zacatecas,56,Zacatecas,114,Tanque la Lama (Los Rodríguez),18,zacatecas,zacatecas,tanque la lama (los rodriguez),zacatecas-tanque la lama (los rodriguez)
299415,32,Zacatecas,56,Zacatecas,96,Tula,2,zacatecas,zacatecas,tula,zacatecas-tula
299441,32,Zacatecas,56,Zacatecas,140,Villa Matute,0,zacatecas,zacatecas,villa matute,zacatecas-villa matute
299381,32,Zacatecas,56,Zacatecas,1,Zacatecas,138444,zacatecas,zacatecas,zacatecas,zacatecas-zacatecas

In [92]:
INEGI_UNIQUELOC_2019_zacatecas.shape

(6418, 11)

In [93]:
INEGI_UNIQUELOC_2019_zacatecas.drop_duplicates(subset=['Municipio_inegi', 'Localidad_inegi'], inplace=True)

In [94]:
INEGI_UNIQUELOC_2019_zacatecas.to_csv('../../data/productores_beneficiarios 2019-2022/diccionarios_E3/2019/INEGI_UNIQUELOC_2019_zacatecas.csv', index=False, encoding='utf-8')

### 1.2.8 INEGI 2019 Localidades únicas para cada año. Veracruz de Ignacio de la Llave

In [95]:
INEGI_UNIQUELOC_2019_veracruz = INEGI_UNIQUELOC_2019[INEGI_UNIQUELOC_2019['Entidad_inegi'] == 'Veracruz de Ignacio de la Llave']

In [96]:
INEGI_UNIQUELOC_2019_veracruz.shape

(27495, 12)

In [97]:
# Ordenar el DataFrame por Entidad_inegi, Municipio_inegi y Localidad_inegi
df_sorted = INEGI_UNIQUELOC_2019_veracruz.sort_values(by=['Entidad_inegi', 'Municipio_inegi', 'Localidad_inegi'])

# Identificar duplicados basados en Entidad_inegi, Municipio_inegi y Localidad_inegi
duplicados = df_sorted[df_sorted.duplicated(subset=['Entidad_inegi', 'Municipio_inegi', 'Localidad_inegi'], keep=False)]
print("Número de rows con base en Entidad, Municipio y Localidad: " , duplicados.shape)

Número de rows con base en Entidad, Municipio y Localidad:  (3749, 12)

In [98]:
# Contar duplicados agrupados por Entidad_inegi, Municipio_inegi y Localidad_inegi
conteo_duplicados = duplicados.groupby(['Entidad_inegi', 'Municipio_inegi', 'Localidad_inegi']).size().reset_index(name='Numero_Duplicados')

# Ordenar por el número de duplicados en orden descendente
conteo_duplicados = conteo_duplicados.sort_values(by='Numero_Duplicados', ascending=False)

# Mostrar el conteo de duplicados ordenado por count
conteo_duplicados

,Entidad_inegi,Municipio_inegi,Localidad_inegi,Numero_Duplicados
734,Veracruz de Ignacio de la Llave,Ozuluama de Mascareñas,La Esperanza,17
716,Veracruz de Ignacio de la Llave,Ozuluama de Mascareñas,El Sacrificio,15
499,Veracruz de Ignacio de la Llave,Las Choapas,San Antonio,9
711,Veracruz de Ignacio de la Llave,Ozuluama de Mascareñas,El Progreso,9
957,Veracruz de Ignacio de la Llave,Pánuco,La Esperanza,9
...,...,...,...,...
552,Veracruz de Ignacio de la Llave,Medellín de Bravo,El Progreso,2
551,Veracruz de Ignacio de la Llave,Medellín de Bravo,El Mangal,2
550,Veracruz de Ignacio de la Llave,Mecayapan,San Rafael,2
549,Veracruz de Ignacio de la Llave,Mecayapan,San José,2
1558,Veracruz de Ignacio de la Llave,Álamo Temapache,Tierra Blanca Booxter,2

In [99]:
conteo_duplicados.shape

(1559, 4)

In [100]:
total_duplicados = conteo_duplicados['Numero_Duplicados'].sum()

In [101]:
total_duplicados

3749

In [102]:
# Step 1 & 2: Group by 'municipio' and 'localidad', then find the row with the maximum 'pob' within each group
INEGI_UNIQUELOC_2019_veracruz = INEGI_UNIQUELOC_2019_veracruz.loc[INEGI_UNIQUELOC_2019_veracruz.groupby(['Municipio_inegi', 'Localidad_inegi'])['POB_TOTAL'].idxmax()]

# This DataFrame now contains the localidades with the greatest 'pob' for each unique 'municipio'-'localidad' combination

In [103]:
INEGI_UNIQUELOC_2019_veracruz.drop(columns=["KEY_inegi_municipio"], inplace=True)

In [104]:
INEGI_UNIQUELOC_2019_veracruz

,CVE_ENT,Entidad_inegi,CVE_MUN,Municipio_inegi,CVE_LOC,Localidad_inegi,POB_TOTAL,Entidad_c_inegi,Municipio_c_inegi,Localidad_c_inegi,KEY_inegi_localidad
255219,30,Veracruz de Ignacio de la Llave,1,Acajete,58,Acajete,44,veracruz de ignacio de la llave,acajete,acajete,acajete-acajete
255194,30,Veracruz de Ignacio de la Llave,1,Acajete,24,Acocota,646,veracruz de ignacio de la llave,acajete,acocota,acajete-acocota
255204,30,Veracruz de Ignacio de la Llave,1,Acajete,42,Alto Pixquiac,0,veracruz de ignacio de la llave,acajete,alto pixquiac,acajete-alto pixquiac
255207,30,Veracruz de Ignacio de la Llave,1,Acajete,46,Barranca Seca,0,veracruz de ignacio de la llave,acajete,barranca seca,acajete-barranca seca
255175,30,Veracruz de Ignacio de la Llave,1,Acajete,2,Barranquillas,149,veracruz de ignacio de la llave,acajete,barranquillas,acajete-barranquillas
...,...,...,...,...,...,...,...,...,...,...,...
276202,30,Veracruz de Ignacio de la Llave,160,Álamo Temapache,149,Zapotitlán Número Dos,434,veracruz de ignacio de la llave,alamo temapache,zapotitlan numero dos,alamo temapache-zapotitlan numero dos
276072,30,Veracruz de Ignacio de la Llave,160,Álamo Temapache,1,Álamo,26236,veracruz de ignacio de la llave,alamo temapache,alamo,alamo temapache-alamo
276352,30,Veracruz de Ignacio de la Llave,160,Álamo Temapache,354,Álamo Tortuga,47,veracruz de ignacio de la llave,alamo temapache,alamo tortuga,alamo temapache-alamo tortuga
276219,30,Veracruz de Ignacio de la Llave,160,Álamo Temapache,171,Úrsulo Galván II,307,veracruz de ignacio de la llave,alamo temapache,ursulo galvan ii,alamo temapache-ursulo galvan ii
276193,30,Veracruz de Ignacio de la Llave,160,Álamo Temapache,139,Úrsulo Galván Uno (El Limonar),1198,veracruz de ignacio de la llave,alamo temapache,ursulo galvan uno (el limonar),alamo temapache-ursulo galvan uno (el limonar)

In [105]:
INEGI_UNIQUELOC_2019_veracruz.shape

(25305, 11)

In [106]:
INEGI_UNIQUELOC_2019_veracruz.drop_duplicates(subset=['Municipio_inegi', 'Localidad_inegi'], inplace=True)

In [107]:
INEGI_UNIQUELOC_2019_veracruz.to_csv('../../data/productores_beneficiarios 2019-2022/diccionarios_E3/2019/INEGI_UNIQUELOC_2019_veracruz.csv', index=False, encoding='utf-8')

### 1.2.9 INEGI 2019 Localidades únicas para cada año. HIDALGO

In [108]:
INEGI_UNIQUELOC_2019_hidalgo = INEGI_UNIQUELOC_2019[INEGI_UNIQUELOC_2019['Entidad_inegi'] == 'Hidalgo']

In [109]:
INEGI_UNIQUELOC_2019_hidalgo.shape

(5354, 12)

In [110]:
# Ordenar el DataFrame por Entidad_inegi, Municipio_inegi y Localidad_inegi
df_sorted = INEGI_UNIQUELOC_2019_hidalgo.sort_values(by=['Entidad_inegi', 'Municipio_inegi', 'Localidad_inegi'])

# Identificar duplicados basados en Entidad_inegi, Municipio_inegi y Localidad_inegi
duplicados = df_sorted[df_sorted.duplicated(subset=['Entidad_inegi', 'Municipio_inegi', 'Localidad_inegi'], keep=False)]
print("Número de rows con base en Entidad, Municipio y Localidad: " , duplicados.shape)

Número de rows con base en Entidad, Municipio y Localidad:  (146, 12)

In [111]:
# Contar duplicados agrupados por Entidad_inegi, Municipio_inegi y Localidad_inegi
conteo_duplicados = duplicados.groupby(['Entidad_inegi', 'Municipio_inegi', 'Localidad_inegi']).size().reset_index(name='Numero_Duplicados')

# Ordenar por el número de duplicados en orden descendente
conteo_duplicados = conteo_duplicados.sort_values(by='Numero_Duplicados', ascending=False)

# Mostrar el conteo de duplicados ordenado por count
conteo_duplicados

   Entidad_inegi Municipio_inegi   Localidad_inegi  Numero_Duplicados
68       Hidalgo         Zimapán           La Loma                  4
33       Hidalgo      Metztitlán  Pie de la Cuesta                  3
12       Hidalgo    Chapulhuacán           La Loma                  3
0        Hidalgo        Almoloya        El Capulín                  2
46       Hidalgo     Singuilucan        San Rafael                  2
..           ...             ...               ...                ...
30       Hidalgo         Metepec           Metepec                  2
31       Hidalgo      Metztitlán            Apanco                  2
32       Hidalgo      Metztitlán           La Laja                  2
34       Hidalgo      Metztitlán     Rincón Grande                  2
70       Hidalgo         Zimapán            Taxthó                  2

[71 rows x 4 columns]

In [112]:
conteo_duplicados.shape

(71, 4)

In [113]:
total_duplicados = conteo_duplicados['Numero_Duplicados'].sum()

In [114]:
total_duplicados

146

In [115]:
# Step 1 & 2: Group by 'municipio' and 'localidad', then find the row with the maximum 'pob' within each group
INEGI_UNIQUELOC_2019_hidalgo = INEGI_UNIQUELOC_2019_hidalgo.loc[INEGI_UNIQUELOC_2019_hidalgo.groupby(['Municipio_inegi', 'Localidad_inegi'])['POB_TOTAL'].idxmax()]

# This DataFrame now contains the localidades with the greatest 'pob' for each unique 'municipio'-'localidad' combination

In [116]:
INEGI_UNIQUELOC_2019_hidalgo.drop(columns=["KEY_inegi_municipio"], inplace=True)

In [117]:
INEGI_UNIQUELOC_2019_hidalgo

,CVE_ENT,Entidad_inegi,CVE_MUN,Municipio_inegi,CVE_LOC,Localidad_inegi,POB_TOTAL,Entidad_c_inegi,Municipio_c_inegi,Localidad_c_inegi,KEY_inegi_localidad
114010,13,Hidalgo,1,Acatlán,27,28 de Mayo (Santa Rosa) [Colonia],2214,hidalgo,acatlan,28 de mayo (santa rosa) [colonia],acatlan-28 de mayo (santa rosa) [colonia]
113986,13,Hidalgo,1,Acatlán,1,Acatlán,439,hidalgo,acatlan,acatlan,acatlan-acatlan
113987,13,Hidalgo,1,Acatlán,2,Agustín Olvera Sección I [Colonia],405,hidalgo,acatlan,agustin olvera seccion i [colonia],acatlan-agustin olvera seccion i [colonia]
113988,13,Hidalgo,1,Acatlán,3,Alcholoya (El Salto de Alcholoya),867,hidalgo,acatlan,alcholoya (el salto de alcholoya),acatlan-alcholoya (el salto de alcholoya)
113989,13,Hidalgo,1,Acatlán,4,Almoloya,1499,hidalgo,acatlan,almoloya,acatlan-almoloya
...,...,...,...,...,...,...,...,...,...,...,...
119227,13,Hidalgo,84,Zimapán,65,Xodhé,17,hidalgo,zimapan,xodhe,zimapan-xodhe
119228,13,Hidalgo,84,Zimapán,66,Yerbabuena,22,hidalgo,zimapan,yerbabuena,zimapan-yerbabuena
119229,13,Hidalgo,84,Zimapán,67,Yethay,96,hidalgo,zimapan,yethay,zimapan-yethay
119167,13,Hidalgo,84,Zimapán,1,Zimapán,14732,hidalgo,zimapan,zimapan,zimapan-zimapan
119171,13,Hidalgo,84,Zimapán,5,Álvaro Obregón (Temuthe),1020,hidalgo,zimapan,alvaro obregon (temuthe),zimapan-alvaro obregon (temuthe)

In [118]:
INEGI_UNIQUELOC_2019_hidalgo.shape

(5279, 11)

In [119]:
INEGI_UNIQUELOC_2019_hidalgo.drop_duplicates(subset=['Municipio_inegi', 'Localidad_inegi'], inplace=True)

In [120]:
INEGI_UNIQUELOC_2019_hidalgo.to_csv('../../data/productores_beneficiarios 2019-2022/diccionarios_E3/2019/INEGI_UNIQUELOC_2019_hidalgo.csv', index=False, encoding='utf-8')

### 1.2.10 INEGI 2019 Localidades únicas para cada año. Michoacán de Ocampo

In [121]:
INEGI_UNIQUELOC_2019_michoacan = INEGI_UNIQUELOC_2019[INEGI_UNIQUELOC_2019['Entidad_inegi'] == 'Michoacán de Ocampo']

In [122]:
INEGI_UNIQUELOC_2019_michoacan.shape

(11789, 12)

In [123]:
# Ordenar el DataFrame por Entidad_inegi, Municipio_inegi y Localidad_inegi
df_sorted = INEGI_UNIQUELOC_2019_michoacan.sort_values(by=['Entidad_inegi', 'Municipio_inegi', 'Localidad_inegi'])

# Identificar duplicados basados en Entidad_inegi, Municipio_inegi y Localidad_inegi
duplicados = df_sorted[df_sorted.duplicated(subset=['Entidad_inegi', 'Municipio_inegi', 'Localidad_inegi'], keep=False)]
print("Número de rows con base en Entidad, Municipio y Localidad: " , duplicados.shape)

Número de rows con base en Entidad, Municipio y Localidad:  (1198, 12)

In [124]:
# Contar duplicados agrupados por Entidad_inegi, Municipio_inegi y Localidad_inegi
conteo_duplicados = duplicados.groupby(['Entidad_inegi', 'Municipio_inegi', 'Localidad_inegi']).size().reset_index(name='Numero_Duplicados')

# Ordenar por el número de duplicados en orden descendente
conteo_duplicados = conteo_duplicados.sort_values(by='Numero_Duplicados', ascending=False)

# Mostrar el conteo de duplicados ordenado por count
conteo_duplicados

,Entidad_inegi,Municipio_inegi,Localidad_inegi,Numero_Duplicados
176,Michoacán de Ocampo,Coalcomán de Vázquez Pallares,El Izote,7
190,Michoacán de Ocampo,Coalcomán de Vázquez Pallares,La Aguacatera,6
272,Michoacán de Ocampo,Huetamo,La Parota,6
173,Michoacán de Ocampo,Coalcomán de Vázquez Pallares,El Guayabillo,5
338,Michoacán de Ocampo,Morelia,Ninguno,5
...,...,...,...,...
192,Michoacán de Ocampo,Coalcomán de Vázquez Pallares,La Carbonera,2
189,Michoacán de Ocampo,Coalcomán de Vázquez Pallares,El Zapote,2
188,Michoacán de Ocampo,Coalcomán de Vázquez Pallares,El Tecolote,2
186,Michoacán de Ocampo,Coalcomán de Vázquez Pallares,El Puertecito,2
527,Michoacán de Ocampo,Álvaro Obregón,San Isidro,2

In [125]:
conteo_duplicados.shape

(528, 4)

In [126]:
total_duplicados = conteo_duplicados['Numero_Duplicados'].sum()

In [127]:
total_duplicados

1198

In [128]:
# Step 1 & 2: Group by 'municipio' and 'localidad', then find the row with the maximum 'pob' within each group
INEGI_UNIQUELOC_2019_michoacan = INEGI_UNIQUELOC_2019_michoacan.loc[INEGI_UNIQUELOC_2019_michoacan.groupby(['Municipio_inegi', 'Localidad_inegi'])['POB_TOTAL'].idxmax()]

# This DataFrame now contains the localidades with the greatest 'pob' for each unique 'municipio'-'localidad' combination

In [129]:
INEGI_UNIQUELOC_2019_michoacan.drop(columns=["KEY_inegi_municipio"], inplace=True)

In [130]:
INEGI_UNIQUELOC_2019_michoacan

,CVE_ENT,Entidad_inegi,CVE_MUN,Municipio_inegi,CVE_LOC,Localidad_inegi,POB_TOTAL,Entidad_c_inegi,Municipio_c_inegi,Localidad_c_inegi,KEY_inegi_localidad
144002,16,Michoacán de Ocampo,1,Acuitzio,1,Acuitzio del Canje,7439,michoacan de ocampo,acuitzio,acuitzio del canje,acuitzio-acuitzio del canje
144028,16,Michoacán de Ocampo,1,Acuitzio,31,Agua Chiquita,0,michoacan de ocampo,acuitzio,agua chiquita,acuitzio-agua chiquita
144029,16,Michoacán de Ocampo,1,Acuitzio,32,Agua Grande,7,michoacan de ocampo,acuitzio,agua grande,acuitzio-agua grande
144030,16,Michoacán de Ocampo,1,Acuitzio,33,Agua Puerca,52,michoacan de ocampo,acuitzio,agua puerca,acuitzio-agua puerca
144006,16,Michoacán de Ocampo,1,Acuitzio,5,Arroyo Hondo,68,michoacan de ocampo,acuitzio,arroyo hondo,acuitzio-arroyo hondo
...,...,...,...,...,...,...,...,...,...,...,...
144368,16,Michoacán de Ocampo,3,Álvaro Obregón,72,Temazcal (La Soledad),357,michoacan de ocampo,alvaro obregon,temazcal (la soledad),alvaro obregon-temazcal (la soledad)
144323,16,Michoacán de Ocampo,3,Álvaro Obregón,3,Tepacua (El Cerrito),148,michoacan de ocampo,alvaro obregon,tepacua (el cerrito),alvaro obregon-tepacua (el cerrito)
144342,16,Michoacán de Ocampo,3,Álvaro Obregón,26,Tzintzimeo,1678,michoacan de ocampo,alvaro obregon,tzintzimeo,alvaro obregon-tzintzimeo
144341,16,Michoacán de Ocampo,3,Álvaro Obregón,24,Zacapendo,226,michoacan de ocampo,alvaro obregon,zacapendo,alvaro obregon-zacapendo
144321,16,Michoacán de Ocampo,3,Álvaro Obregón,1,Álvaro Obregón,9513,michoacan de ocampo,alvaro obregon,alvaro obregon,alvaro obregon-alvaro obregon

In [131]:
INEGI_UNIQUELOC_2019_michoacan.shape

(11119, 11)

In [132]:
INEGI_UNIQUELOC_2019_michoacan.drop_duplicates(subset=['Municipio_inegi', 'Localidad_inegi'], inplace=True)

In [133]:
INEGI_UNIQUELOC_2019_michoacan.to_csv('../../data/productores_beneficiarios 2019-2022/diccionarios_E3/2019/INEGI_UNIQUELOC_2019_michoacan.csv', index=False, encoding='utf-8')

### 1.2.11 INEGI 2019 Localidades únicas para cada año. OAXACA

In [134]:
INEGI_UNIQUELOC_2019_oaxaca = INEGI_UNIQUELOC_2019[INEGI_UNIQUELOC_2019['Entidad_inegi'] == 'Oaxaca']

In [135]:
INEGI_UNIQUELOC_2019_oaxaca.shape

(13000, 12)

In [136]:
# Ordenar el DataFrame por Entidad_inegi, Municipio_inegi y Localidad_inegi
df_sorted = INEGI_UNIQUELOC_2019_oaxaca.sort_values(by=['Entidad_inegi', 'Municipio_inegi', 'Localidad_inegi'])

# Identificar duplicados basados en Entidad_inegi, Municipio_inegi y Localidad_inegi
duplicados = df_sorted[df_sorted.duplicated(subset=['Entidad_inegi', 'Municipio_inegi', 'Localidad_inegi'], keep=False)]
print("Número de rows con base en Entidad, Municipio y Localidad: " , duplicados.shape)

Número de rows con base en Entidad, Municipio y Localidad:  (344, 12)

In [137]:
# Contar duplicados agrupados por Entidad_inegi, Municipio_inegi y Localidad_inegi
conteo_duplicados = duplicados.groupby(['Entidad_inegi', 'Municipio_inegi', 'Localidad_inegi']).size().reset_index(name='Numero_Duplicados')

# Ordenar por el número de duplicados en orden descendente
conteo_duplicados = conteo_duplicados.sort_values(by='Numero_Duplicados', ascending=False)

# Mostrar el conteo de duplicados ordenado por count
conteo_duplicados

,Entidad_inegi,Municipio_inegi,Localidad_inegi,Numero_Duplicados
106,Oaxaca,San Pedro Tapanatepec,San Antonio,4
75,Oaxaca,San Juan Cotzocón,Los Tres Hermanos,4
138,Oaxaca,Santiago Yaveo,La Esperanza,4
135,Oaxaca,Santiago Yaveo,El Coyolito,3
35,Oaxaca,Loma Bonita,El Olvido,3
...,...,...,...,...
58,Oaxaca,San Esteban Atatlahuca,Loma Larga,2
59,Oaxaca,San Francisco del Mar,Los Cocos,2
60,Oaxaca,San Francisco del Mar,San Antonio,2
61,Oaxaca,San Jerónimo Coatlán,El Mirador,2
163,Oaxaca,Villa de Tututepec,Vista Hermosa,2

In [138]:
conteo_duplicados.shape

(164, 4)

In [139]:
total_duplicados = conteo_duplicados['Numero_Duplicados'].sum()

In [140]:
total_duplicados

344

In [141]:
# Step 1 & 2: Group by 'municipio' and 'localidad', then find the row with the maximum 'pob' within each group
INEGI_UNIQUELOC_2019_oaxaca = INEGI_UNIQUELOC_2019_oaxaca.loc[INEGI_UNIQUELOC_2019_oaxaca.groupby(['Municipio_inegi', 'Localidad_inegi'])['POB_TOTAL'].idxmax()]

# This DataFrame now contains the localidades with the greatest 'pob' for each unique 'municipio'-'localidad' combination

In [142]:
INEGI_UNIQUELOC_2019_oaxaca.drop(columns=["KEY_inegi_municipio"], inplace=True)

In [143]:
INEGI_UNIQUELOC_2019_oaxaca

,CVE_ENT,Entidad_inegi,CVE_MUN,Municipio_inegi,CVE_LOC,Localidad_inegi,POB_TOTAL,Entidad_c_inegi,Municipio_c_inegi,Localidad_c_inegi,KEY_inegi_localidad
173398,20,Oaxaca,1,Abejones,1,Abejones,841,oaxaca,abejones,abejones,abejones-abejones
173399,20,Oaxaca,2,Acatlán de Pérez Figueroa,1,Acatlán de Pérez Figueroa,6341,oaxaca,acatlan de perez figueroa,acatlan de perez figueroa,acatlan de perez figueroa-acatlan de perez fig...
173400,20,Oaxaca,2,Acatlán de Pérez Figueroa,2,Agua Escondida,10,oaxaca,acatlan de perez figueroa,agua escondida,acatlan de perez figueroa-agua escondida
173401,20,Oaxaca,2,Acatlán de Pérez Figueroa,3,Arroyo de Enmedio,1517,oaxaca,acatlan de perez figueroa,arroyo de enmedio,acatlan de perez figueroa-arroyo de enmedio
173402,20,Oaxaca,2,Acatlán de Pérez Figueroa,4,Arroyo de Pita,766,oaxaca,acatlan de perez figueroa,arroyo de pita,acatlan de perez figueroa-arroyo de pita
...,...,...,...,...,...,...,...,...,...,...,...
177818,20,Oaxaca,174,Ánimas Trujano,4,El Paredón,6,oaxaca,animas trujano,el paredon,animas trujano-el paredon
177817,20,Oaxaca,174,Ánimas Trujano,3,El Zapotillo,282,oaxaca,animas trujano,el zapotillo,animas trujano-el zapotillo
177820,20,Oaxaca,174,Ánimas Trujano,6,La Ciénega,14,oaxaca,animas trujano,la cienega,animas trujano-la cienega
177819,20,Oaxaca,174,Ánimas Trujano,5,La Tortuga [Paraje],35,oaxaca,animas trujano,la tortuga [paraje],animas trujano-la tortuga [paraje]
177816,20,Oaxaca,174,Ánimas Trujano,1,Ánimas Trujano,4227,oaxaca,animas trujano,animas trujano,animas trujano-animas trujano

In [144]:
INEGI_UNIQUELOC_2019_oaxaca.shape

(12820, 11)

In [145]:
INEGI_UNIQUELOC_2019_oaxaca.drop_duplicates(subset=['Municipio_inegi', 'Localidad_inegi'], inplace=True)

In [146]:
INEGI_UNIQUELOC_2019_oaxaca.to_csv('../../data/productores_beneficiarios 2019-2022/diccionarios_E3/2019/INEGI_UNIQUELOC_2019_oaxaca.csv', index=False, encoding='utf-8')

### 1.2.12 INEGI 2019 Localidades únicas para cada año. COLIMA

In [147]:
INEGI_UNIQUELOC_2019_colima = INEGI_UNIQUELOC_2019[INEGI_UNIQUELOC_2019['Entidad_inegi'] == 'Colima']

In [148]:
INEGI_UNIQUELOC_2019_colima.shape

(2872, 12)

In [149]:
# Ordenar el DataFrame por Entidad_inegi, Municipio_inegi y Localidad_inegi
df_sorted = INEGI_UNIQUELOC_2019_colima.sort_values(by=['Entidad_inegi', 'Municipio_inegi', 'Localidad_inegi'])

# Identificar duplicados basados en Entidad_inegi, Municipio_inegi y Localidad_inegi
duplicados = df_sorted[df_sorted.duplicated(subset=['Entidad_inegi', 'Municipio_inegi', 'Localidad_inegi'], keep=False)]
print("Número de rows con base en Entidad, Municipio y Localidad: " , duplicados.shape)

Número de rows con base en Entidad, Municipio y Localidad:  (392, 12)

In [150]:
# Contar duplicados agrupados por Entidad_inegi, Municipio_inegi y Localidad_inegi
conteo_duplicados = duplicados.groupby(['Entidad_inegi', 'Municipio_inegi', 'Localidad_inegi']).size().reset_index(name='Numero_Duplicados')

# Ordenar por el número de duplicados en orden descendente
conteo_duplicados = conteo_duplicados.sort_values(by='Numero_Duplicados', ascending=False)

# Mostrar el conteo de duplicados ordenado por count
conteo_duplicados

    Entidad_inegi   Municipio_inegi Localidad_inegi  Numero_Duplicados
149        Colima           Tecomán        San José                  8
153        Colima           Tecomán      San Miguel                  8
120        Colima           Tecomán    La Primavera                  6
143        Colima           Tecomán    Rancho Viejo                  5
118        Colima           Tecomán       La Parota                  5
..            ...               ...             ...                ...
60         Colima       Coquimatlán  Las Primaveras                  2
61         Colima       Coquimatlán      San Isidro                  2
62         Colima        Cuauhtémoc      El Establo                  2
63         Colima        Cuauhtémoc    Juan Alcaraz                  2
166        Colima  Villa de Álvarez     Las Parotas                  2

[167 rows x 4 columns]

In [151]:
conteo_duplicados.shape

(167, 4)

In [152]:
total_duplicados = conteo_duplicados['Numero_Duplicados'].sum()

In [153]:
total_duplicados

392

In [154]:
# Step 1 & 2: Group by 'municipio' and 'localidad', then find the row with the maximum 'pob' within each group
INEGI_UNIQUELOC_2019_colima = INEGI_UNIQUELOC_2019_colima.loc[INEGI_UNIQUELOC_2019_colima.groupby(['Municipio_inegi', 'Localidad_inegi'])['POB_TOTAL'].idxmax()]

# This DataFrame now contains the localidades with the greatest 'pob' for each unique 'municipio'-'localidad' combination

In [155]:
INEGI_UNIQUELOC_2019_colima.drop(columns=["KEY_inegi_municipio"], inplace=True)

In [156]:
INEGI_UNIQUELOC_2019_colima

,CVE_ENT,Entidad_inegi,CVE_MUN,Municipio_inegi,CVE_LOC,Localidad_inegi,POB_TOTAL,Entidad_c_inegi,Municipio_c_inegi,Localidad_c_inegi,KEY_inegi_localidad
29789,6,Colima,1,Armería,358,Alejandro Martínez,0,colima,armeria,alejandro martinez,armeria-alejandro martinez
29707,6,Colima,1,Armería,203,Amador Cázares,0,colima,armeria,amador cazares,armeria-amador cazares
29663,6,Colima,1,Armería,45,Augusto Gómez Villanueva (Coalatilla),1347,colima,armeria,augusto gomez villanueva (coalatilla),armeria-augusto gomez villanueva (coalatilla)
29697,6,Colima,1,Armería,191,Barba Azul,15,colima,armeria,barba azul,armeria-barba azul
29749,6,Colima,1,Armería,278,Boca de Río [Jesús Gallegos],0,colima,armeria,boca de rio [jesus gallegos],armeria-boca de rio [jesus gallegos]
...,...,...,...,...,...,...,...,...,...,...,...
32437,6,Colima,10,Villa de Álvarez,231,Santa Lucía,0,colima,villa de alvarez,santa lucia,villa de alvarez-santa lucia
32373,6,Colima,10,Villa de Álvarez,48,Trapichillos,0,colima,villa de alvarez,trapichillos,villa de alvarez-trapichillos
32407,6,Colima,10,Villa de Álvarez,146,Tres Pitayos (Minatitlán),0,colima,villa de alvarez,tres pitayos (minatitlan),villa de alvarez-tres pitayos (minatitlan)
32513,6,Colima,10,Villa de Álvarez,367,Valle Encantado,0,colima,villa de alvarez,valle encantado,villa de alvarez-valle encantado
32385,6,Colima,10,Villa de Álvarez,96,Vista Hermosa,0,colima,villa de alvarez,vista hermosa,villa de alvarez-vista hermosa

In [157]:
INEGI_UNIQUELOC_2019_colima.shape

(2647, 11)

In [158]:
INEGI_UNIQUELOC_2019_colima.drop_duplicates(subset=['Municipio_inegi', 'Localidad_inegi'], inplace=True)

In [159]:
INEGI_UNIQUELOC_2019_colima.to_csv('../../data/productores_beneficiarios 2019-2022/diccionarios_E3/2019/INEGI_UNIQUELOC_2019_colima.csv', index=False, encoding='utf-8')

### 1.2.13 INEGI 2019 Localidades únicas para cada año. San Luis Potosí

In [160]:
INEGI_UNIQUELOC_2019_potosi = INEGI_UNIQUELOC_2019[INEGI_UNIQUELOC_2019['Entidad_inegi'] == 'San Luis Potosí']

In [161]:
INEGI_UNIQUELOC_2019_potosi.shape

(9221, 12)

In [162]:
# Ordenar el DataFrame por Entidad_inegi, Municipio_inegi y Localidad_inegi
df_sorted = INEGI_UNIQUELOC_2019_potosi.sort_values(by=['Entidad_inegi', 'Municipio_inegi', 'Localidad_inegi'])

# Identificar duplicados basados en Entidad_inegi, Municipio_inegi y Localidad_inegi
duplicados = df_sorted[df_sorted.duplicated(subset=['Entidad_inegi', 'Municipio_inegi', 'Localidad_inegi'], keep=False)]
print("Número de rows con base en Entidad, Municipio y Localidad: " , duplicados.shape)

Número de rows con base en Entidad, Municipio y Localidad:  (502, 12)

In [163]:
# Contar duplicados agrupados por Entidad_inegi, Municipio_inegi y Localidad_inegi
conteo_duplicados = duplicados.groupby(['Entidad_inegi', 'Municipio_inegi', 'Localidad_inegi']).size().reset_index(name='Numero_Duplicados')

# Ordenar por el número de duplicados en orden descendente
conteo_duplicados = conteo_duplicados.sort_values(by='Numero_Duplicados', ascending=False)

# Mostrar el conteo de duplicados ordenado por count
conteo_duplicados

       Entidad_inegi Municipio_inegi Localidad_inegi  Numero_Duplicados
224  San Luis Potosí         Xilitla    Rancho Nuevo                  6
43   San Luis Potosí   Ciudad Valles    Rancho Nuevo                  5
41   San Luis Potosí   Ciudad Valles         Ninguno                  5
179  San Luis Potosí          Tamuín    Santa Martha                  4
47   San Luis Potosí   Ciudad Valles   San Francisco                  4
..               ...             ...             ...                ...
88   San Luis Potosí        Rioverde    Las Adjuntas                  2
89   San Luis Potosí        Rioverde     Las Águilas                  2
90   San Luis Potosí        Rioverde    Los Alamitos                  2
91   San Luis Potosí        Rioverde     Ojo de Agua                  2
226  San Luis Potosí        Zaragoza      Las Trojes                  2

[227 rows x 4 columns]

In [164]:
conteo_duplicados.shape

(227, 4)

In [165]:
total_duplicados = conteo_duplicados['Numero_Duplicados'].sum()

In [166]:
total_duplicados

502

In [167]:
# Step 1 & 2: Group by 'municipio' and 'localidad', then find the row with the maximum 'pob' within each group
INEGI_UNIQUELOC_2019_potosi = INEGI_UNIQUELOC_2019_potosi.loc[INEGI_UNIQUELOC_2019_potosi.groupby(['Municipio_inegi', 'Localidad_inegi'])['POB_TOTAL'].idxmax()]

# This DataFrame now contains the localidades with the greatest 'pob' for each unique 'municipio'-'localidad' combination

In [168]:
INEGI_UNIQUELOC_2019_potosi.drop(columns=["KEY_inegi_municipio"], inplace=True)

In [169]:
INEGI_UNIQUELOC_2019_potosi

,CVE_ENT,Entidad_inegi,CVE_MUN,Municipio_inegi,CVE_LOC,Localidad_inegi,POB_TOTAL,Entidad_c_inegi,Municipio_c_inegi,Localidad_c_inegi,KEY_inegi_localidad
201512,24,San Luis Potosí,1,Ahualulco,1,Ahualulco del Sonido 13,5249,san luis potosi,ahualulco,ahualulco del sonido 13,ahualulco-ahualulco del sonido 13
201515,24,San Luis Potosí,1,Ahualulco,5,Arenal de Morelos,141,san luis potosi,ahualulco,arenal de morelos,ahualulco-arenal de morelos
201558,24,San Luis Potosí,1,Ahualulco,52,Arroyo Blanco,58,san luis potosi,ahualulco,arroyo blanco,ahualulco-arroyo blanco
201516,24,San Luis Potosí,1,Ahualulco,6,Barrancas,611,san luis potosi,ahualulco,barrancas,ahualulco-barrancas
201519,24,San Luis Potosí,1,Ahualulco,9,Casita Blanca,26,san luis potosi,ahualulco,casita blanca,ahualulco-casita blanca
...,...,...,...,...,...,...,...,...,...,...,...
210307,24,San Luis Potosí,55,Zaragoza,131,Valle de los Fantasmas,204,san luis potosi,zaragoza,valle de los fantasmas,zaragoza-valle de los fantasmas
210221,24,San Luis Potosí,55,Zaragoza,1,Villa de Zaragoza,11425,san luis potosi,zaragoza,villa de zaragoza,zaragoza-villa de zaragoza
210292,24,San Luis Potosí,55,Zaragoza,101,Xoconoxtle,826,san luis potosi,zaragoza,xoconoxtle,zaragoza-xoconoxtle
210227,24,San Luis Potosí,55,Zaragoza,7,Álvarez,30,san luis potosi,zaragoza,alvarez,zaragoza-alvarez
210369,24,San Luis Potosí,55,Zaragoza,214,Ángel Hernández,0,san luis potosi,zaragoza,angel hernandez,zaragoza-angel hernandez

In [170]:
INEGI_UNIQUELOC_2019_potosi.shape

(8946, 11)

In [171]:
INEGI_UNIQUELOC_2019_potosi.drop_duplicates(subset=['Municipio_inegi', 'Localidad_inegi'], inplace=True)

In [172]:
INEGI_UNIQUELOC_2019_potosi.to_csv('../../data/productores_beneficiarios 2019-2022/diccionarios_E3/2019/INEGI_UNIQUELOC_2019_potosi.csv', index=False, encoding='utf-8')

### 1.2.14 INEGI 2019 Localidades únicas para cada año. JALISCO

In [173]:
INEGI_UNIQUELOC_2019_jalisco = INEGI_UNIQUELOC_2019[INEGI_UNIQUELOC_2019['Entidad_inegi'] == 'Jalisco']

In [174]:
INEGI_UNIQUELOC_2019_jalisco.shape

(19400, 12)

In [175]:
# Ordenar el DataFrame por Entidad_inegi, Municipio_inegi y Localidad_inegi
df_sorted = INEGI_UNIQUELOC_2019_jalisco.sort_values(by=['Entidad_inegi', 'Municipio_inegi', 'Localidad_inegi'])

# Identificar duplicados basados en Entidad_inegi, Municipio_inegi y Localidad_inegi
duplicados = df_sorted[df_sorted.duplicated(subset=['Entidad_inegi', 'Municipio_inegi', 'Localidad_inegi'], keep=False)]
print("Número de rows con base en Entidad, Municipio y Localidad: " , duplicados.shape)

Número de rows con base en Entidad, Municipio y Localidad:  (1947, 12)

In [176]:
# Contar duplicados agrupados por Entidad_inegi, Municipio_inegi y Localidad_inegi
conteo_duplicados = duplicados.groupby(['Entidad_inegi', 'Municipio_inegi', 'Localidad_inegi']).size().reset_index(name='Numero_Duplicados')

# Ordenar por el número de duplicados en orden descendente
conteo_duplicados = conteo_duplicados.sort_values(by='Numero_Duplicados', ascending=False)

# Mostrar el conteo de duplicados ordenado por count
conteo_duplicados

    Entidad_inegi     Municipio_inegi      Localidad_inegi  Numero_Duplicados
366       Jalisco           Mezquitic            El Zapote                 10
377       Jalisco           Mezquitic            La Laguna                  9
438       Jalisco           Mezquitic        Tierra Blanca                  7
145       Jalisco           El Grullo              Ninguno                  7
380       Jalisco           Mezquitic              La Mesa                  7
..            ...                 ...                  ...                ...
292       Jalisco     Lagos de Moreno          Las Huertas                  2
293       Jalisco     Lagos de Moreno          Las Palomas                  2
294       Jalisco     Lagos de Moreno  Loma de San Antonio                  2
295       Jalisco     Lagos de Moreno         Los Alamitos                  2
852       Jalisco  Zapotlán el Grande              Ninguno                  2

[853 rows x 4 columns]

In [177]:
conteo_duplicados.shape

(853, 4)

In [178]:
total_duplicados = conteo_duplicados['Numero_Duplicados'].sum()

In [179]:
total_duplicados

1947

In [180]:
# Step 1 & 2: Group by 'municipio' and 'localidad', then find the row with the maximum 'pob' within each group
INEGI_UNIQUELOC_2019_jalisco = INEGI_UNIQUELOC_2019_jalisco.loc[INEGI_UNIQUELOC_2019_jalisco.groupby(['Municipio_inegi', 'Localidad_inegi'])['POB_TOTAL'].idxmax()]

# This DataFrame now contains the localidades with the greatest 'pob' for each unique 'municipio'-'localidad' combination

In [181]:
INEGI_UNIQUELOC_2019_jalisco.drop(columns=["KEY_inegi_municipio"], inplace=True)

In [182]:
INEGI_UNIQUELOC_2019_jalisco

,CVE_ENT,Entidad_inegi,CVE_MUN,Municipio_inegi,CVE_LOC,Localidad_inegi,POB_TOTAL,Entidad_c_inegi,Municipio_c_inegi,Localidad_c_inegi,KEY_inegi_localidad
119340,14,Jalisco,1,Acatic,1,Acatic,13033,jalisco,acatic,acatic,acatic-acatic
119455,14,Jalisco,1,Acatic,142,Acatic (Colonia la Prepa),565,jalisco,acatic,acatic (colonia la prepa),acatic-acatic (colonia la prepa)
119425,14,Jalisco,1,Acatic,107,Agropecuaria Calderón,60,jalisco,acatic,agropecuaria calderon,acatic-agropecuaria calderon
119341,14,Jalisco,1,Acatic,2,Agua Prieta (Tepetates),221,jalisco,acatic,agua prieta (tepetates),acatic-agua prieta (tepetates)
119342,14,Jalisco,1,Acatic,3,Alacates,7,jalisco,acatic,alacates,acatic-alacates
...,...,...,...,...,...,...,...,...,...,...,...
122566,14,Jalisco,23,Zapotlán el Grande,211,Tabla Larga,6,jalisco,zapotlan el grande,tabla larga,zapotlan el grande-tabla larga
122592,14,Jalisco,23,Zapotlán el Grande,238,Talpita,4,jalisco,zapotlan el grande,talpita,zapotlan el grande-talpita
122585,14,Jalisco,23,Zapotlán el Grande,231,Valle de Zapotlán,0,jalisco,zapotlan el grande,valle de zapotlan,zapotlan el grande-valle de zapotlan
122572,14,Jalisco,23,Zapotlán el Grande,217,Zacatón (Zacatoncillo),0,jalisco,zapotlan el grande,zacaton (zacatoncillo),zapotlan el grande-zacaton (zacatoncillo)
122577,14,Jalisco,23,Zapotlán el Grande,222,Zapotlán 2000 [Parque Industrial],714,jalisco,zapotlan el grande,zapotlan 2000 [parque industrial],zapotlan el grande-zapotlan 2000 [parque indus...

In [183]:
INEGI_UNIQUELOC_2019_jalisco.shape

(18306, 11)

In [184]:
INEGI_UNIQUELOC_2019_jalisco.drop_duplicates(subset=['Municipio_inegi', 'Localidad_inegi'], inplace=True)

In [185]:
INEGI_UNIQUELOC_2019_jalisco.to_csv('../../data/productores_beneficiarios 2019-2022/diccionarios_E3/2019/INEGI_UNIQUELOC_2019_jalisco.csv', index=False, encoding='utf-8')

### 1.2.15 INEGI 2019 Localidades únicas para cada año. NAYARIT

In [186]:
INEGI_UNIQUELOC_2019_nayarit = INEGI_UNIQUELOC_2019[INEGI_UNIQUELOC_2019['Entidad_inegi'] == 'Nayarit']

In [187]:
INEGI_UNIQUELOC_2019_nayarit.shape

(4946, 12)

In [188]:
# Ordenar el DataFrame por Entidad_inegi, Municipio_inegi y Localidad_inegi
df_sorted = INEGI_UNIQUELOC_2019_nayarit.sort_values(by=['Entidad_inegi', 'Municipio_inegi', 'Localidad_inegi'])

# Identificar duplicados basados en Entidad_inegi, Municipio_inegi y Localidad_inegi
duplicados = df_sorted[df_sorted.duplicated(subset=['Entidad_inegi', 'Municipio_inegi', 'Localidad_inegi'], keep=False)]
print("Número de rows con base en Entidad, Municipio y Localidad: " , duplicados.shape)

Número de rows con base en Entidad, Municipio y Localidad:  (774, 12)

In [189]:
# Contar duplicados agrupados por Entidad_inegi, Municipio_inegi y Localidad_inegi
conteo_duplicados = duplicados.groupby(['Entidad_inegi', 'Municipio_inegi', 'Localidad_inegi']).size().reset_index(name='Numero_Duplicados')

# Ordenar por el número de duplicados en orden descendente
conteo_duplicados = conteo_duplicados.sort_values(by='Numero_Duplicados', ascending=False)

# Mostrar el conteo de duplicados ordenado por count
conteo_duplicados

    Entidad_inegi Municipio_inegi Localidad_inegi  Numero_Duplicados
210       Nayarit        La Yesca      La Ciénega                  9
247       Nayarit        La Yesca    Los Llanitos                  8
203       Nayarit        La Yesca     El Ranchito                  8
86        Nayarit       Del Nayar       El Zapote                  8
246       Nayarit        La Yesca    Los Cerritos                  7
..            ...             ...             ...                ...
134       Nayarit       Del Nayar       Pajaritos                  2
135       Nayarit       Del Nayar         Palomas                  2
136       Nayarit       Del Nayar        Picachos                  2
137       Nayarit       Del Nayar      Platanitos                  2
301       Nayarit           Tepic       Tepetilte                  2

[302 rows x 4 columns]

In [190]:
conteo_duplicados.shape

(302, 4)

In [191]:
total_duplicados = conteo_duplicados['Numero_Duplicados'].sum()

In [192]:
total_duplicados

774

In [193]:
# Step 1 & 2: Group by 'municipio' and 'localidad', then find the row with the maximum 'pob' within each group
INEGI_UNIQUELOC_2019_nayarit = INEGI_UNIQUELOC_2019_nayarit.loc[INEGI_UNIQUELOC_2019_nayarit.groupby(['Municipio_inegi', 'Localidad_inegi'])['POB_TOTAL'].idxmax()]

# This DataFrame now contains the localidades with the greatest 'pob' for each unique 'municipio'-'localidad' combination

In [194]:
INEGI_UNIQUELOC_2019_nayarit.drop(columns=["KEY_inegi_municipio"], inplace=True)

In [195]:
INEGI_UNIQUELOC_2019_nayarit

,CVE_ENT,Entidad_inegi,CVE_MUN,Municipio_inegi,CVE_LOC,Localidad_inegi,POB_TOTAL,Entidad_c_inegi,Municipio_c_inegi,Localidad_c_inegi,KEY_inegi_localidad
157717,18,Nayarit,1,Acaponeta,1,Acaponeta,19976,nayarit,acaponeta,acaponeta,acaponeta-acaponeta
157902,18,Nayarit,1,Acaponeta,342,Agua Buena,0,nayarit,acaponeta,agua buena,acaponeta-agua buena
157874,18,Nayarit,1,Acaponeta,307,Agua Plascencia [Purificadora],1,nayarit,acaponeta,agua plascencia [purificadora],acaponeta-agua plascencia [purificadora]
157826,18,Nayarit,1,Acaponeta,205,Agua Tendida,3,nayarit,acaponeta,agua tendida,acaponeta-agua tendida
157720,18,Nayarit,1,Acaponeta,7,Amado Nervo,85,nayarit,acaponeta,amado nervo,acaponeta-amado nervo
...,...,...,...,...,...,...,...,...,...,...,...
159019,18,Nayarit,8,Xalisco,122,San Rafael [Rancho],3,nayarit,xalisco,san rafael [rancho],xalisco-san rafael [rancho]
158954,18,Nayarit,8,Xalisco,21,Testerazo,2811,nayarit,xalisco,testerazo,xalisco-testerazo
158955,18,Nayarit,8,Xalisco,22,Trigomil,691,nayarit,xalisco,trigomil,xalisco-trigomil
158937,18,Nayarit,8,Xalisco,1,Xalisco,48170,nayarit,xalisco,xalisco,xalisco-xalisco
159015,18,Nayarit,8,Xalisco,118,Yoreme [Rancho],6,nayarit,xalisco,yoreme [rancho],xalisco-yoreme [rancho]

In [196]:
INEGI_UNIQUELOC_2019_nayarit.shape

(4474, 11)

In [197]:
INEGI_UNIQUELOC_2019_nayarit.drop_duplicates(subset=['Municipio_inegi', 'Localidad_inegi'], inplace=True)

In [198]:
INEGI_UNIQUELOC_2019_nayarit.to_csv('../../data/productores_beneficiarios 2019-2022/diccionarios_E3/2019/INEGI_UNIQUELOC_2019_nayarit.csv', index=False, encoding='utf-8')

### 1.2.16 INEGI 2019 Localidades únicas para cada año. Guerrero

In [199]:
INEGI_UNIQUELOC_2019_guerrero_minuscula = INEGI_UNIQUELOC_2019[INEGI_UNIQUELOC_2019['Entidad_inegi'] == 'Guerrero']

In [200]:
INEGI_UNIQUELOC_2019_guerrero_minuscula.shape

(9551, 12)

In [201]:
# Ordenar el DataFrame por Entidad_inegi, Municipio_inegi y Localidad_inegi
df_sorted = INEGI_UNIQUELOC_2019_guerrero_minuscula.sort_values(by=['Entidad_inegi', 'Municipio_inegi', 'Localidad_inegi'])

# Identificar duplicados basados en Entidad_inegi, Municipio_inegi y Localidad_inegi
duplicados = df_sorted[df_sorted.duplicated(subset=['Entidad_inegi', 'Municipio_inegi', 'Localidad_inegi'], keep=False)]
print("Número de rows con base en Entidad, Municipio y Localidad: " , duplicados.shape)

Número de rows con base en Entidad, Municipio y Localidad:  (647, 12)

In [202]:
# Contar duplicados agrupados por Entidad_inegi, Municipio_inegi y Localidad_inegi
conteo_duplicados = duplicados.groupby(['Entidad_inegi', 'Municipio_inegi', 'Localidad_inegi']).size().reset_index(name='Numero_Duplicados')

# Ordenar por el número de duplicados en orden descendente
conteo_duplicados = conteo_duplicados.sort_values(by='Numero_Duplicados', ascending=False)

# Mostrar el conteo de duplicados ordenado por count
conteo_duplicados

,Entidad_inegi,Municipio_inegi,Localidad_inegi,Numero_Duplicados
257,Guerrero,Zirándaro,El Guayabo,6
279,Guerrero,Zirándaro,Las Juntas,5
208,Guerrero,Técpan de Galeana,El Rincón,5
39,Guerrero,Coahuayutla de José María Izazaga,El Jazmín,4
286,Guerrero,Zirándaro,Potrerillos,4
...,...,...,...,...
110,Guerrero,Cutzamala de Pinzón,Las Juntas,2
111,Guerrero,Cutzamala de Pinzón,Loma Bonita,2
113,Guerrero,Florencio Villarreal,Vista Hermosa,2
114,Guerrero,General Heliodoro Castillo,Barrio Nuevo,2
145,Guerrero,Olinalá,Los Mangos,2

In [203]:
conteo_duplicados.shape

(290, 4)

In [204]:
total_duplicados = conteo_duplicados['Numero_Duplicados'].sum()

In [205]:
total_duplicados

647

In [206]:
# Step 1 & 2: Group by 'municipio' and 'localidad', then find the row with the maximum 'pob' within each group
INEGI_UNIQUELOC_2019_guerrero_minuscula = INEGI_UNIQUELOC_2019_guerrero_minuscula.loc[INEGI_UNIQUELOC_2019_guerrero_minuscula.groupby(['Municipio_inegi', 'Localidad_inegi'])['POB_TOTAL'].idxmax()]

# This DataFrame now contains the localidades with the greatest 'pob' for each unique 'municipio'-'localidad' combination

In [207]:
INEGI_UNIQUELOC_2019_guerrero_minuscula.drop(columns=["KEY_inegi_municipio"], inplace=True)

In [208]:
INEGI_UNIQUELOC_2019_guerrero_minuscula

,CVE_ENT,Entidad_inegi,CVE_MUN,Municipio_inegi,CVE_LOC,Localidad_inegi,POB_TOTAL,Entidad_c_inegi,Municipio_c_inegi,Localidad_c_inegi,KEY_inegi_localidad
104542,12,Guerrero,1,Acapulco de Juárez,377,10 de Abril,879,guerrero,acapulco de juarez,10 de abril,acapulco de juarez-10 de abril
104721,12,Guerrero,1,Acapulco de Juárez,758,13 de Diciembre,19,guerrero,acapulco de juarez,13 de diciembre,acapulco de juarez-13 de diciembre
104435,12,Guerrero,1,Acapulco de Juárez,1,Acapulco de Juárez,658609,guerrero,acapulco de juarez,acapulco de juarez,acapulco de juarez-acapulco de juarez
104572,12,Guerrero,1,Acapulco de Juárez,462,Agropecuaria,0,guerrero,acapulco de juarez,agropecuaria,acapulco de juarez-agropecuaria
104652,12,Guerrero,1,Acapulco de Juárez,666,Agua Salada [Estación Hidrométrica],0,guerrero,acapulco de juarez,agua salada [estacion hidrometrica],acapulco de juarez-agua salada [estacion hidro...
...,...,...,...,...,...,...,...,...,...,...,...
113404,12,Guerrero,74,Zitlala,34,Totola,73,guerrero,zitlala,totola,zitlala-totola
113395,12,Guerrero,74,Zitlala,20,Viramontes,415,guerrero,zitlala,viramontes,zitlala-viramontes
113396,12,Guerrero,74,Zitlala,22,Yetlancingo,639,guerrero,zitlala,yetlancingo,zitlala-yetlancingo
113403,12,Guerrero,74,Zitlala,32,Zacayahutla,0,guerrero,zitlala,zacayahutla,zitlala-zacayahutla
113377,12,Guerrero,74,Zitlala,1,Zitlala,6077,guerrero,zitlala,zitlala,zitlala-zitlala

In [209]:
INEGI_UNIQUELOC_2019_guerrero_minuscula.shape

(9194, 11)

In [210]:
INEGI_UNIQUELOC_2019_guerrero_minuscula.drop_duplicates(subset=['Municipio_inegi', 'Localidad_inegi'], inplace=True)

In [211]:
INEGI_UNIQUELOC_2019_guerrero_minuscula.to_csv('../../data/productores_beneficiarios 2019-2022/diccionarios_E3/2019/INEGI_UNIQUELOC_2019_guerrero_minuscula.csv', index=False, encoding='utf-8')