# CARGA DE DATOS

In [1]:
import pandas as pd
import seaborn as sns

def load_datasets():
    ags_df = pd.read_csv('datasets/anexo_unico_i_1er_listado_autori_fertilizantes_23_ags_convo_1.csv', encoding='cp1252', index_col=0, skiprows=1)
    cdmx_df = pd.read_csv('datasets/anexo_unico_i_1er_listado_autori_fertilizantes_23_cdmx_convo_1.csv', encoding='cp1252', index_col=0, skiprows=1)
    chp_df = pd.read_csv('datasets/anexo_unico_i_1er_listado_autori_fertilizantes_23_chp_convo_1.csv', encoding='cp1252', index_col=0, skiprows=1)
    cmp_df = pd.read_csv('datasets/anexo_unico_i_1er_listado_autori_fertilizantes_23_cmp_convo_1.csv', encoding='cp1252', index_col=0, skiprows=1)
    col_df = pd.read_csv('datasets/anexo_unico_i_1er_listado_autori_fertilizantes_23_col_convo_1.csv', encoding='cp1252', index_col=0, skiprows=1)
    dgo_df = pd.read_csv('datasets/anexo_unico_i_1er_listado_autori_fertilizantes_23_dgo_convo_1.csv', encoding='cp1252', index_col=0, skiprows=1)
    edo_mch_df = pd.read_csv('datasets/anexo_unico_i_1er_listado_autori_fertilizantes_23_edo_mch_convo_1.csv', encoding='cp1252', index_col=0, skiprows=1)
    edo_mex_df = pd.read_csv('datasets/anexo_unico_i_1er_listado_autori_fertilizantes_23_edo_mex_convo_1.csv', encoding='cp1252', index_col=0, skiprows=1)
    edo_mex_df2 = pd.read_csv('datasets/anexo_unico_i_1er_listado_autori_fertilizantes_23_edo_mex_convo_2.csv', encoding='cp1252', index_col=0, skiprows=1)
    edo_mex_df3 = pd.read_csv('datasets/anexo_unico_i_1er_listado_autori_fertilizantes_23_edo_mex_convo_3.csv', encoding='cp1252', index_col=0, skiprows=1)
    edo_mor_df = pd.read_csv('datasets/anexo_unico_i_1er_listado_autori_fertilizantes_23_edo_mor_convo_1.csv', encoding='cp1252', index_col=0, skiprows=1)
    gro_df = pd.read_csv('datasets/anexo_unico_i_1er_listado_autori_fertilizantes_23_gro_convo_1.csv', encoding='cp1252', index_col=0, skiprows=1)
    hgo_df = pd.read_csv('datasets/anexo_unico_i_1er_listado_autori_fertilizantes_23_hgo_convo_1.csv', encoding='cp1252', index_col=0, skiprows=1)
    jal_df = pd.read_csv('datasets/anexo_unico_i_1er_listado_autori_fertilizantes_23_jal_convo_1.csv', encoding='cp1252', index_col=0, skiprows=1)
    mor_df = pd.read_csv('datasets/anexo_unico_i_1er_listado_autori_fertilizantes_23_mor_convo_2.csv', encoding='cp1252', index_col=0, skiprows=1)
    oax_df = pd.read_csv('datasets/anexo_unico_i_1er_listado_autori_fertilizantes_23_oax_convo_1.csv', encoding='cp1252', index_col=0, skiprows=1)
    pbl_df = pd.read_csv('datasets/anexo_unico_i_1er_listado_autori_fertilizantes_23_pbl_convo_1.csv', encoding='cp1252', index_col=0, skiprows=1)
    qnro_df = pd.read_csv('datasets/anexo_unico_i_1er_listado_autori_fertilizantes_23_qnro_convo_1.csv', encoding='cp1252', index_col=0, skiprows=1)
    qro_df = pd.read_csv('datasets/anexo_unico_i_1er_listado_autori_fertilizantes_23_qro_convo_1.csv', encoding='cp1252', index_col=0, skiprows=1)
    txl_df = pd.read_csv('datasets/anexo_unico_i_1er_listado_autori_fertilizantes_23_txl_convo_1.csv', encoding='cp1252', index_col=0, skiprows=1)
    vrz_df = pd.read_csv('datasets/anexo_unico_i_1er_listado_autori_fertilizantes_23_vrz_convo_1.csv', encoding='cp1252', index_col=0, skiprows=1)
    yct_df = pd.read_csv('datasets/anexo_unico_i_1er_listado_autori_fertilizantes_23_yct_convo_1.csv', encoding='cp1252', index_col=0, skiprows=1)
    gro2_df = pd.read_csv('datasets/anexo_unico_i_2do_listado_autori_fertilizantes_23_gro_convo_1.csv', encoding='cp1252', index_col=0, skiprows=1)
    jal2_df = pd.read_csv('datasets/anexo_unico_i_2do_listado_autori_fertilizantes_23_jal_convo_1.csv', encoding='cp1252', index_col=0, skiprows=1)
    pbl2_df = pd.read_csv('datasets/anexo_unico_i_2do_listado_autori_fertilizantes_23_pbl_convo_1.csv', encoding='cp1252', index_col=0, skiprows=1)

    list = [ags_df, cdmx_df, chp_df, cmp_df, col_df, dgo_df, edo_mch_df, edo_mex_df, edo_mex_df2, edo_mex_df3, edo_mor_df, gro_df, hgo_df, jal_df, mor_df, oax_df, pbl_df, qnro_df, qro_df, txl_df, vrz_df, yct_df, gro2_df, jal2_df, pbl2_df]
    
    merged_df = pd.concat(list, join='inner', ignore_index=True)

    return merged_df

In [2]:
inegi_df = pd.read_csv('dataset_inegi/dataset_inegi.csv', encoding='cp1252', index_col=0)

In [3]:
inegi_df

,Estatus,CVE_ENT,NOM_ENT,NOM_ABR,CVE_MUN,NOM_MUN,CVE_LOC,NOM_LOC,AMBITO,LATITUD,LONGITUD,LAT_DECIMAL,LON_DECIMAL,ALTITUD,CVE_CARTA,POB_TOTAL,POB_MASCULINA,POB_FEMENINA,TOTAL DE VIVIENDAS HABITADAS
MAPA,,,,,,,,,,,,,,,,,,,
10010001,NaN,1,Aguascalientes,Ags.,1,Aguascalientes,1,Aguascalientes,U,"21°52´47.362N""","102°17´45.768W""",21.879822,-102.296046,1878,F13D19,863893,419168,444725,246259
10010094,NaN,1,Aguascalientes,Ags.,1,Aguascalientes,94,Granja Adelita,R,"21°52´18.749N""","102°22´24.710W""",21.871874,-102.373530,1901,F13D18,5,*,*,2
10010096,NaN,1,Aguascalientes,Ags.,1,Aguascalientes,96,Agua Azul,R,"21°53´01.522N""","102°21´25.639W""",21.883756,-102.357122,1861,F13D18,41,24,17,12
10010100,NaN,1,Aguascalientes,Ags.,1,Aguascalientes,100,Rancho Alegre,R,"21°51´16.556N""","102°22´21.884W""",21.854599,-102.372745,1879,F13D18,0,0,0,0
10010102,NaN,1,Aguascalientes,Ags.,1,Aguascalientes,102,Los Arbolitos [Rancho],R,"21°46´48.650N""","102°21´26.261W""",21.780180,-102.357295,1861,F13D18,8,*,*,2
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
320580039,NaN,32,Zacatecas,Zac.,58,Santa María de la Paz,39,San Isidro,R,"21°29´11.130N""","103°20´14.164W""",21.486425,-103.337267,2036,F13D35,1,*,*,1
320580040,NaN,32,Zacatecas,Zac.,58,Santa María de la Paz,40,San José,R,"21°30´59.539N""","103°27´23.645W""",21.516539,-103.456568,1821,F13D25,0,0,0,0
320580041,NaN,32,Zacatecas,Zac.,58,Santa María de la Paz,41,San Miguel Tepetitlán,R,"21°30´15.168N""","103°20´09.356W""",21.504213,-103.335932,1977,F13D25,97,47,50,31
320580042,NaN,32,Zacatecas,Zac.,58,Santa María de la Paz,42,San Rafael,R,"21°31´39.341N""","103°22´20.134W""",21.527594,-103.372259,2041,F13D25,3,*,*,1
320580043,NaN,32,Zacatecas,Zac.,58,Santa María de la Paz,43,Santa Fe,R,"21°31´44.371N""","103°23´06.343W""",21.528991,-103.385095,2021,F13D25,0,0,0,0

In [4]:
df = load_datasets()
df

,ESTADO,MUNICIPIO,ACUSE,APELLIDO PATERNO,APELLIDO MATERNO,NOMBRE (S),PAQUETE
0,AGUASCALIENTES,AGUASCALIENTES,23-PRONAFE-FERT-000510-S000-AS,AGUILAR,AGUILAR,NICOLAS,2
1,AGUASCALIENTES,AGUASCALIENTES,23-PRONAFE-FERT-000339-S000-AS,AGUILAR,GARCIA,MANUEL,2
2,AGUASCALIENTES,AGUASCALIENTES,23-PRONAFE-FERT-000340-S000-AS,AGUILAR,GARCIA,PAULO,2
3,AGUASCALIENTES,AGUASCALIENTES,23-PRONAFE-FERT-000511-S000-AS,AGUILAR,OROPEZA,MIGUEL,2
4,AGUASCALIENTES,AGUASCALIENTES,23-PRONAFE-FERT-000676-S000-AS,ALBA,ESTRADA,MARIA DEL ROSARIO,2
...,...,...,...,...,...,...,...
1525715,PUEBLA,ZOQUITLAN,23-PRONAFE-FERT-103370-S000-PL,NaN,NaN,NaN,2
1525716,PUEBLA,ZOQUITLAN,23-PRONAFE-FERT-103371-S000-PL,NaN,NaN,NaN,2
1525717,PUEBLA,ZOQUITLAN,23-PRONAFE-FERT-103166-S000-PL,NaN,NaN,NaN,2
1525718,PUEBLA,ZOQUITLAN,23-PRONAFE-FERT-103373-S000-PL,NaN,NaN,NaN,2
1525719,PUEBLA,ZOQUITLAN,23-PRONAFE-FERT-103374-S000-PL,NaN,NaN,NaN,2

In [5]:
df.columns

Index(['ESTADO', 'MUNICIPIO', 'ACUSE', 'APELLIDO PATERNO', 'APELLIDO MATERNO',
       'NOMBRE (S)', 'PAQUETE'],
      dtype='object')

In [6]:
df

,ESTADO,MUNICIPIO,ACUSE,APELLIDO PATERNO,APELLIDO MATERNO,NOMBRE (S),PAQUETE
0,AGUASCALIENTES,AGUASCALIENTES,23-PRONAFE-FERT-000510-S000-AS,AGUILAR,AGUILAR,NICOLAS,2
1,AGUASCALIENTES,AGUASCALIENTES,23-PRONAFE-FERT-000339-S000-AS,AGUILAR,GARCIA,MANUEL,2
2,AGUASCALIENTES,AGUASCALIENTES,23-PRONAFE-FERT-000340-S000-AS,AGUILAR,GARCIA,PAULO,2
3,AGUASCALIENTES,AGUASCALIENTES,23-PRONAFE-FERT-000511-S000-AS,AGUILAR,OROPEZA,MIGUEL,2
4,AGUASCALIENTES,AGUASCALIENTES,23-PRONAFE-FERT-000676-S000-AS,ALBA,ESTRADA,MARIA DEL ROSARIO,2
...,...,...,...,...,...,...,...
1525715,PUEBLA,ZOQUITLAN,23-PRONAFE-FERT-103370-S000-PL,NaN,NaN,NaN,2
1525716,PUEBLA,ZOQUITLAN,23-PRONAFE-FERT-103371-S000-PL,NaN,NaN,NaN,2
1525717,PUEBLA,ZOQUITLAN,23-PRONAFE-FERT-103166-S000-PL,NaN,NaN,NaN,2
1525718,PUEBLA,ZOQUITLAN,23-PRONAFE-FERT-103373-S000-PL,NaN,NaN,NaN,2
1525719,PUEBLA,ZOQUITLAN,23-PRONAFE-FERT-103374-S000-PL,NaN,NaN,NaN,2

In [7]:
df.columns

Index(['ESTADO', 'MUNICIPIO', 'ACUSE', 'APELLIDO PATERNO', 'APELLIDO MATERNO',
       'NOMBRE (S)', 'PAQUETE'],
      dtype='object')

In [8]:
df.dtypes

ESTADO              object
MUNICIPIO           object
ACUSE               object
APELLIDO PATERNO    object
APELLIDO MATERNO    object
NOMBRE (S)          object
PAQUETE              int64
dtype: object

In [9]:
df = df.astype({
    'ESTADO' : 'string',
    'MUNICIPIO' : 'string',
    'ACUSE' : 'string',
    'APELLIDO PATERNO' : 'string',
    'APELLIDO MATERNO' : 'string',
    'NOMBRE (S)' : 'string',
})

In [10]:
df.dtypes

ESTADO              string
MUNICIPIO           string
ACUSE               string
APELLIDO PATERNO    string
APELLIDO MATERNO    string
NOMBRE (S)          string
PAQUETE              int64
dtype: object

# VALORES DUPLICADOS

In [11]:
duplicate_rows_df = df[df.duplicated()]
duplicate_rows_df.shape

(0, 7)

In [12]:
# Remove duplicates
df = df.drop_duplicates()

In [13]:
duplicate_rows_df = df[df.duplicated()]
duplicate_rows_df.shape

(0, 7)

# FORMATEAR STRINGS

In [14]:
def clean_text(text):
    text = text.str.strip()  # Eliminar espacios en blanco
    text = text.str.lower()  # Convertir a minúsculas
    text = text.str.replace('[^a-zA-Z\s]', '')  # Eliminar caracteres especiales
    text = text.str.replace('\s+', ' ')  # Eliminar espacios en blanco extras
    text = text.str.replace('^\s+|\s+?$', '')  # Eliminar espacios al inicio y al final
    return text

In [15]:
columns_to_clean = ['ESTADO', 'MUNICIPIO']

In [16]:
for col in columns_to_clean:
    df[col] = clean_text(df[col])

/var/folders/ng/n9ng0wy92t90_49j662nh02c0000gn/T/ipykernel_33677/3083008952.py:4: FutureWarning: The default value of regex will change from True to False in a future version.
  text = text.str.replace('[^a-zA-Z\s]', '')  # Eliminar caracteres especiales
/var/folders/ng/n9ng0wy92t90_49j662nh02c0000gn/T/ipykernel_33677/3083008952.py:5: FutureWarning: The default value of regex will change from True to False in a future version.
  text = text.str.replace('\s+', ' ')  # Eliminar espacios en blanco extras
/var/folders/ng/n9ng0wy92t90_49j662nh02c0000gn/T/ipykernel_33677/3083008952.py:6: FutureWarning: The default value of regex will change from True to False in a future version.
  text = text.str.replace('^\s+|\s+?$', '')  # Eliminar espacios al inicio y al final

In [17]:
df['ESTADO'] = df['ESTADO'].str.title()
df['MUNICIPIO'] = df['MUNICIPIO'].str.title()

In [18]:
df

,ESTADO,MUNICIPIO,ACUSE,APELLIDO PATERNO,APELLIDO MATERNO,NOMBRE (S),PAQUETE
0,Aguascalientes,Aguascalientes,23-PRONAFE-FERT-000510-S000-AS,AGUILAR,AGUILAR,NICOLAS,2
1,Aguascalientes,Aguascalientes,23-PRONAFE-FERT-000339-S000-AS,AGUILAR,GARCIA,MANUEL,2
2,Aguascalientes,Aguascalientes,23-PRONAFE-FERT-000340-S000-AS,AGUILAR,GARCIA,PAULO,2
3,Aguascalientes,Aguascalientes,23-PRONAFE-FERT-000511-S000-AS,AGUILAR,OROPEZA,MIGUEL,2
4,Aguascalientes,Aguascalientes,23-PRONAFE-FERT-000676-S000-AS,ALBA,ESTRADA,MARIA DEL ROSARIO,2
...,...,...,...,...,...,...,...
1525715,Puebla,Zoquitlan,23-PRONAFE-FERT-103370-S000-PL,<NA>,<NA>,<NA>,2
1525716,Puebla,Zoquitlan,23-PRONAFE-FERT-103371-S000-PL,<NA>,<NA>,<NA>,2
1525717,Puebla,Zoquitlan,23-PRONAFE-FERT-103166-S000-PL,<NA>,<NA>,<NA>,2
1525718,Puebla,Zoquitlan,23-PRONAFE-FERT-103373-S000-PL,<NA>,<NA>,<NA>,2
1525719,Puebla,Zoquitlan,23-PRONAFE-FERT-103374-S000-PL,<NA>,<NA>,<NA>,2

# Valores faltantes

In [19]:
df.isna().sum()

ESTADO                  0
MUNICIPIO           75512
ACUSE                   0
APELLIDO PATERNO     4294
APELLIDO MATERNO    28213
NOMBRE (S)           4293
PAQUETE                 0
dtype: int64

In [20]:
(df == 0).sum()

ESTADO              0
MUNICIPIO           0
ACUSE               0
APELLIDO PATERNO    0
APELLIDO MATERNO    0
NOMBRE (S)          0
PAQUETE             0
dtype: int64

In [21]:
df[df.isnull().any(axis=1)]

,ESTADO,MUNICIPIO,ACUSE,APELLIDO PATERNO,APELLIDO MATERNO,NOMBRE (S),PAQUETE
84,Aguascalientes,Aguascalientes,23-PRONAFE-FERT-000688-S000-AS,CORTEZ,<NA>,AMELIA,2
141,Aguascalientes,Aguascalientes,23-PRONAFE-FERT-000662-S000-AS,DIAZ,<NA>,CONSUELO,2
295,Aguascalientes,Aguascalientes,23-PRONAFE-FERT-000309-S000-AS,HERNANDEZ,<NA>,MA. TERESA,2
443,Aguascalientes,Aguascalientes,23-PRONAFE-FERT-000190-S000-AS,MARTINEZ,<NA>,AGUSTIN,2
518,Aguascalientes,Aguascalientes,23-PRONAFE-FERT-000568-S000-AS,ORTEGA,<NA>,ROMALDO,2
...,...,...,...,...,...,...,...
1525715,Puebla,Zoquitlan,23-PRONAFE-FERT-103370-S000-PL,<NA>,<NA>,<NA>,2
1525716,Puebla,Zoquitlan,23-PRONAFE-FERT-103371-S000-PL,<NA>,<NA>,<NA>,2
1525717,Puebla,Zoquitlan,23-PRONAFE-FERT-103166-S000-PL,<NA>,<NA>,<NA>,2
1525718,Puebla,Zoquitlan,23-PRONAFE-FERT-103373-S000-PL,<NA>,<NA>,<NA>,2
1525719,Puebla,Zoquitlan,23-PRONAFE-FERT-103374-S000-PL,<NA>,<NA>,<NA>,2

Si no hay nombre del productor acreditado lo quitamos. También en el caso de que no haya apellido paterno. Un valor sin nombre y apellido no tiene uso práctico alguno.

In [22]:
df = df.dropna(subset=['NOMBRE (S)'])
df = df.dropna(subset=['APELLIDO PATERNO'])

In [23]:
df.isna().sum()

ESTADO                  0
MUNICIPIO           75512
ACUSE                   0
APELLIDO PATERNO        0
APELLIDO MATERNO    23920
NOMBRE (S)              0
PAQUETE                 0
dtype: int64

# ORTOGRAFÍA

In [24]:
# Get unique values in df
unique_estado_df = df['ESTADO'].unique()
unique_municipio_df = df['MUNICIPIO'].unique()

# Get unique values in inegi_df
unique_nom_ent_inegi = inegi_df['NOM_ENT'].unique()
unique_nom_mun_inegi = inegi_df['NOM_MUN'].unique()

In [25]:
unique_estado_df_list = list(unique_estado_df)
unique_municipio_df_list = list(unique_municipio_df)
unique_nom_ent_inegi_list = list(unique_nom_ent_inegi)
unique_nom_mun_inegi_list = list(unique_nom_mun_inegi)

# Create a DataFrame
unique_values_df = pd.DataFrame({
    'ESTADO': pd.Series(unique_estado_df_list),
    'MUNICIPIO': pd.Series(unique_municipio_df_list),
    'NOM_ENT': pd.Series(unique_nom_ent_inegi_list),
    'NOM_MUN': pd.Series(unique_nom_mun_inegi_list)
})

In [26]:
df['ESTADO'] = df['ESTADO'].replace('Mxico', 'Mexico')

In [27]:
unique_values_df.head(50)

,ESTADO,MUNICIPIO,NOM_ENT,NOM_MUN
0,Aguascalientes,Aguascalientes,Aguascalientes,Aguascalientes
1,Ciudad De Mexico,Asientos,Baja California,Asientos
2,Chiapas,Calvillo,Baja California Sur,Calvillo
3,Campeche,Cosio,Campeche,Cosío
4,Colima,El Llano,Coahuila de Zaragoza,Jesús María
5,Durango,Jesus Maria,Colima,Pabellón de Arteaga
6,Michoacan De Ocampo,Pabellon De Arteaga,Chiapas,Rincón de Romos
7,Mexico,Rincon De Romos,Chihuahua,San José de Gracia
8,Mxico,San Francisco De Los Romo,Ciudad de México,Tepezalá
9,Morelos,San Jose De Gracia,Durango,El Llano
10,Guerrero,Tepezala,Guanajuato,San Francisco de los Romo
11,Hidalgo,Alvaro Obregon,Guerrero,Ensenada
12,Jalisco,Coyoacan,Hidalgo,Mexicali
13,Oaxaca,Cuajimalpa De Morelos,Jalisco,Tecate
14,Puebla,Iztapalapa,México,Tijuana
15,Quintana Roo,La Magdalena Contreras,Michoacán de Ocampo,Playas de Rosarito
16,Queretaro De Arteaga,Milpa Alta,Morelos,San Quintín
17,Tlaxcala,Tlahuac,Nayarit,San Felipe
18,Veracruz De Ignacio De La Llave,Tlalpan,Nuevo León,Comondú
19,Yucatan,Xochimilco,Oaxaca,Mulegé
20,NaN,Acacoyagua,Puebla,La Paz
21,NaN,Acala,Querétaro,Los Cabos
22,NaN,Acapetahua,Quintana Roo,Loreto
23,NaN,Aldama,San Luis Potosí,Calkiní
24,NaN,Altamirano,Sinaloa,Campeche
25,NaN,Amatan,Sonora,Carmen
26,NaN,Amatenango De La Frontera,Tabasco,Champotón
27,NaN,Amatenango Del Valle,Tamaulipas,Hecelchakán
28,NaN,Angel Albino Corzo,Tlaxcala,Hopelchén
29,NaN,Arriaga,Veracruz de Ignacio de la Llave,Palizada
30,NaN,Bejucal De Ocampo,Yucatán,Tenabo
31,NaN,Belisario Dominguez,Zacatecas,Escárcega
32,NaN,Bella Vista,NaN,Calakmul
33,NaN,Benemerito De Las Americas,NaN,Candelaria
34,NaN,Berriozabal,NaN,Seybaplaya
35,NaN,Bochil,NaN,Dzitbalché
36,NaN,Cacahoatan,NaN,Abasolo
37,NaN,Catazaja,NaN,Acuña
38,NaN,Chalchihuitan,NaN,Allende
39,NaN,Chamula,NaN,Arteaga
40,NaN,Chanal,NaN,Candela
41,NaN,Chapultenango,NaN,Castaños
42,NaN,Chenalho,NaN,Cuatro Ciénegas
43,NaN,Chiapa De Corzo,NaN,Escobedo
44,NaN,Chiapilla,NaN,Francisco I. Madero
45,NaN,Chicoasen,NaN,Frontera
46,NaN,Chicomuselo,NaN,General Cepeda
47,NaN,Chilon,NaN,Guerrero
48,NaN,Cintalapa,NaN,Hidalgo
49,NaN,Coapilla,NaN,Jiménez

# VALORES ATÍPICOS

In [28]:
df.reset_index(level=0, inplace=True)

In [29]:
df

,index,ESTADO,MUNICIPIO,ACUSE,APELLIDO PATERNO,APELLIDO MATERNO,NOMBRE (S),PAQUETE
0,0,Aguascalientes,Aguascalientes,23-PRONAFE-FERT-000510-S000-AS,AGUILAR,AGUILAR,NICOLAS,2
1,1,Aguascalientes,Aguascalientes,23-PRONAFE-FERT-000339-S000-AS,AGUILAR,GARCIA,MANUEL,2
2,2,Aguascalientes,Aguascalientes,23-PRONAFE-FERT-000340-S000-AS,AGUILAR,GARCIA,PAULO,2
3,3,Aguascalientes,Aguascalientes,23-PRONAFE-FERT-000511-S000-AS,AGUILAR,OROPEZA,MIGUEL,2
4,4,Aguascalientes,Aguascalientes,23-PRONAFE-FERT-000676-S000-AS,ALBA,ESTRADA,MARIA DEL ROSARIO,2
...,...,...,...,...,...,...,...,...
1521421,1521422,Puebla,Santiago Miahuatlan,23-PRONAFE-FERT-075885-S000-PL,VAZQUEZ,NIETO,JOSE MANUEL,2
1521422,1521423,Puebla,Santiago Miahuatlan,23-PRONAFE-FERT-075894-S000-PL,ZENTENO,CRUZ,ANGEL DAVID,2
1521423,1521424,Puebla,Santo Tomas Hueyotlipan,23-PRONAFE-FERT-075946-S000-PL,GONZALEZ,ROMERO,SABINA,1
1521424,1521425,Puebla,Santo Tomas Hueyotlipan,23-PRONAFE-FERT-075947-S000-PL,GONZALEZ,ZAYAS,MIRIAM,2
1521425,1521426,Puebla,Santo Tomas Hueyotlipan,23-PRONAFE-FERT-075921-S000-PL,ZAYAS,RAMIREZ,GUILLERMO,2

In [30]:
df.to_csv('productores_autorizados/productores_autorizados_fertilizantes.csv', index=False)